// Generated by tools/split_runner.py -- the shared internals of the
// Runner goal families. Everything here came verbatim out of the old
// src/life/Runner.cpp anonymous namespace; the only edits are `inline`
// on the free functions and the namespace becoming named.
//
// The four TABLE ACCESSORS below hold function-local statics that
// Runner::Configure fills and other families read. They are declared here
// and DEFINED ONCE in RunnerShared.cpp on purpose: an inline/header copy
// would give every translation unit its own empty table.
#pragma once

#include "life/Runner.h"

#include "Client.h"
#include "uo/log.h"
#include "uo/builders.h"
#include "uo/faucets.h"
#include "uo/activities/acquire.h"
#include "uo/activities/gather.h"
#include "uo/activities/craft_confirm.h"
#include "uo/activities/tame.h"
#include "uo/activities/train.h"
#include "uo/activities/train_confirm.h"
#include "uo/interaction/progress.h"
#include "uo/market.h"
#include "uo/newbie_knowledge.h"
#include "uo/trade.h"
#include "uo/combat.h"
#include "uo/professions.h"
#include "uo/sphere_rules.h"
#include "uo/vendor_policy.h"
#include "uo/world_model.h"

#include <algorithm>
#include <cstdarg>
#include <cstdio>
#include <unordered_map>
#include <cstring>

namespace uo::life {
namespace runner_detail {

// --- defined once in RunnerShared.cpp --------------------------------
std::string Fmt2(const char* fmt, ...);
GoalKind ProducingGoalFor(const std::string& item);


// Item graphics, all read off the runtime's own itemdefs -- never guessed from
// generic UO tables. i_hatchet is [ITEMDEF 0f43] with DUPELIST 0f44 (the
// flipped graphic); i_log is 0x1BDD; i_bandage is [ITEMDEF 0e21].
constexpr u16 kHatchet[]  = {0x0F43, 0x0F44};
constexpr u16 kAxe[]      = {0x0F49, 0x0F4A};
constexpr u16 kLog        = 0x1BDD;
constexpr u16 kBandage    = 0x0E21;
// Every heal potion is the same yellow bottle -- HealLess, Heal and HealGreat
// are all ID=i_bottle_yellow -- so this counts strength-blind, which is what
// a player squinting at their own pack does too.
constexpr u16 kHealPotion = 0x0F0C;

// SHIRT, TROUSERS, SHOES. Not armour and not decoration -- what a person
// wears so as not to be standing in a city in their underwear. Plain and
// cheap on purpose: a tailor's shirt is 2-24 gold and a cobbler's shoes 2-6
// (tm_vend.scp VENDOR_S_TAILOR, VENDOR_S_COBBLER).
struct ClothingPiece {
    u16         graphic;   // what to BUY when the slot is empty
    const char* item;      // defname, for the buy request
    const char* what;      // for the log
    // WHO SELLS IT FIRST. A cobbler does not stock trousers, and the first
    // live run walked to one for a pair: the seller list is tried in order,
    // so a single shared order sends every garment to the wrong counter twice
    // out of three times. Cloth to the tailor, footwear to the cobbler.
    const char* firstSeller;
    // ANYTHING THAT FILLS THE SAME SLOT COUNTS AS FILLING IT. Naming one
    // graphic per slot made the bot shop for what it was already carrying:
    // "you have shhort pants on your bag" (project owner, 2026-08-30) while
    // it walked to a cobbler for long ones. A player wears the trousers they
    // own. Zero-terminated.
    u16 alsoWorn[8];
};
constexpr ClothingPiece kBasicClothing[] = {
    {0x1517, "i_shirt_plain", "shirt",    "tailor",
     {0x1517, 0x1EFD, 0x25EA, 0, 0, 0, 0, 0}},         // plain, fancy, checkered
    {0x1539, "i_pants_long",  "trousers", "tailor",
     {0x1539, 0x152E, 0x279B, 0x1537, 0, 0, 0, 0}},    // long, short, tattsuke, kilt
    {0x170F, "i_shoes_plain", "shoes",    "cobbler",
     {0x170F, 0x170B, 0x1711, 0x170D, 0x2307, 0x2796, 0x2797, 0}},
                                                               // shoes, boots, sandals, fur, tabi
};

// Is this slot already dealt with -- worn, or in the pack ready to wear?
// Returns the pack serial when there is something to put on, 0 otherwise, and
// sets `worn` when the slot is already filled.
inline u32 ClothingOnHand(Client& client, const ClothingPiece& p, bool* worn) {
    *worn = false;
    for (const u16 g : p.alsoWorn) {
        if (!g) break;
        const u8 layer = client.ItemEquipLayer(g);
        if (!layer) continue;
        if (client.EquippedGraphicAt(layer)) { *worn = true; return 0; }
    }
    for (const u16 g : p.alsoWorn) {
        if (!g) break;
        if (const u32 have = client.FindBackpackItemByGraphic(g)) return have;
    }
    return 0;
}
constexpr u16 kKatana[]   = {0x13FE, 0x13FF};
// The other three weapon-school basics (kryss/club/bow) live as
// life::SchoolWeapon rows in uo/life.h / life/Identity.cpp, not here --
// see SchoolWeaponFor, used by DoReplaceEquipment below.
// WHAT THIS SHARD ACTUALLY SELLS AS FOOD, read from its own itemdefs rather
// than from generic UO. The first three were all the old list had, and a
// baker's window is mostly none of them -- Voris stood in front of pizzas and
// pans of cookies with an empty stomach.
//
//   0x103B i_bread_loaf     0x1041 i_pie_baked    0x09E9 i_cake
//   0x09EA i_muffin         0x098C i_bread_french 0x160B i_pan_cookies
//   0x1040 i_pizza          0x160A i_lamb_leg     0x1608 i_chicken_leg
//   0x09B7 i_bird_cooked    0x09C9 i_ham          0x09EB/0x09F2 kept from
//                                                 the original list
//
// 0x097B i_fish_cut_cooked is a fisher's own supper and was missing, so a
// fisher STARVED with dinner in its pack: the eat branch found nothing it
// recognised, fell through to the "cut and cook the catch" stand-down, and
// stood the errand down again every few minutes without ever eating (live
// 2026-09-02: run_gates/g_Dorvar.console.txt:584 "You are starving" with
// i_fish_cut_cooked carried, and lines 276/1313/2367/3455 standing down).
// It is TYPE=t_food on this shard
// (runtime/scripts/items/i_profession_cook_barkeep_baker.scp:113-115).
constexpr u16 kFood[]     = {0x103B, 0x1041, 0x09E9, 0x09EA, 0x098C, 0x160B,
                             0x1040, 0x160A, 0x1608, 0x09B7, 0x09C9,
                             0x09EB, 0x09F2, 0x097B};
constexpr u16 kGoldCoin   = 0x0EED;             // i_gold
// i_tongs (0FBB/0FBC) and i_hammer_smith (013E3, dupe 013E4) are both
// TYPE=t_weapon_mace_smith, which is what the engine gates the menu on.
constexpr u16 kSmithToolGfx[] = {0x0FBB, 0x0FBC, 0x13E3, 0x13E4};
// BUT ONLY THE HAMMER CAN BE WIELDED, and the menu needs it in HAND1.
// i_tongs has no DAM and no SKILL in i_profession.scp -- it is not a weapon,
// so the server will not put it in a hand: it answered "You put the tongs in
// your pack" to every equip, at layer 0 and layer 1, with the hand empty.
// i_hammer_smith has DAM=13,15 SKILL=Macefighting and equips normally.
// "equip smith hammer maybe?" (project owner, 2026-08-29).
constexpr u16 kSmithHammerGfx[] = {0x13E3, 0x13E4};
// WHAT OPENS A CRAFT MENU, per tool.
//
// Most trades open their menu by double-clicking the TOOL, not the material:
// a mortar for alchemy, tinker tools, a sewing kit, a saw. Inscription is the
// exception the enum itself names -- Tool::BlankScroll, "Inscription's menu
// opens by double-clicking one" -- which is why DoCraft's default was written
// around the material and why alchemy then answered "You can't think of a way
// to use that item" as it double-clicked a reagent.
//
// Graphics come from Professions.cpp, which reads them off the shard's own
// itemdefs: mortar 0E9B, sewing kit 0F9D, saw 1034, tinker tools 1EBC.
struct ToolOpener { prod::Tool tool; u16 gfx[4]; usize n; };
const ToolOpener kToolOpeners[] = {
    {prod::Tool::MortarPestle,  {0x0E9B, 0, 0, 0},        1},
    {prod::Tool::SewingKit,     {0x0F9D, 0, 0, 0},        1},
    {prod::Tool::CarpentryTool, {0x1034, 0, 0, 0},        1},
    {prod::Tool::TinkerTools,   {0x1EBC, 0, 0, 0},        1},
    {prod::Tool::Scissors,      {0x0F9E, 0x0F9F, 0, 0},   2},
    {prod::Tool::SmithHammer,   {0x13E3, 0x13E4, 0, 0},   2},
};
inline const ToolOpener* OpenerFor(prod::Tool t) {
    for (const ToolOpener& o : kToolOpeners) if (o.tool == t) return &o;
    return nullptr;
}

// WEAPONS A FIGHTER MIGHT BE CARRYING. Every one of these is handed out by the
// shard's own newbie kits (sp_tm_newbie.scp: [NEWBIE FENCING] ITEMNEWBIE=
// i_kryss, [NEWBIE MACEFIGHTING] i_club, [NEWBIE SWORDSMANSHIP] and friends),
// and they are ITEMNEWBIE, so they survive death. Kaelen's own saved character
// carries i_kryss, i_dagger AND i_katana -- all three sitting in CONT=
// (his backpack) with no LAYER, which is to say in his bag while he punched a
// Spectre bare-handed for twenty seconds and called it a stalemate.
// Flip pairs included: a weapon on the wire is often the flipped id.
constexpr u16 kMeleeWeaponGfx[] = {
    0x1400, 0x1401,   // i_kryss
    0x0F51, 0x0F52,   // i_dagger
    0x13B3, 0x13B4,   // i_club
    0x13FE, 0x13FF,   // i_katana
    0x0F5E, 0x0F5F,   // i_sword_broad
    0x1440, 0x1441,   // i_sword_cutlass
    0x0F60, 0x0F61,   // i_sword_long
    0x143B, 0x143C,   // i_mace
    0x0F62, 0x0F63,   // i_spear
};
// Enough coin to walk into a shop with. A smith hammer is VALUE=50 and the
// dearest tool a life buys is well under this, so one withdrawal covers the
// errand rather than one trip to the box per item.
constexpr i32 kToolMoneyToCarry = 500;
// i_spellbook, ITEMDEF 0efa. A spell scroll's graphic is 0x1F2D + the spell
// number: Create Food is spell 2 at 0x1F2F, Heal is 4 at 0x1F31, Magic Arrow
// is 5 at 0x1F32 and Recall is 31 at 0x1F4C -- four independent points, all
// read from this shard's own itemdefs. Circles 1-8 are therefore spells 1-64
// at 0x1F2E..0x1F6D.
// A working book rather than a complete one: circles 7-8 are sold by nobody
// on this shard, so a target of 64 would nag forever. 24 is the first three
// circles, which ARE obtainable by shopping. Mirrors kSpellbookComfortable in
// Needs.cpp -- the need and the goal must agree or the goal finishes a book
// the need still wants filled, and the pair loops.
constexpr int kSpellbookComfortableRuntime = 24;
// Enough to be worth a trip. Prices come from the shop window, never from
// here; these are only "is it worth walking".
constexpr i32 kSpellbookMoney = 120;
constexpr i32 kScrollMoney    = 120;
constexpr i64 kNoSpellbookCooldownMs = 240000;   // four minutes
// A book with no self-castable spell in it is FILL_SPELLBOOK's problem, and
// that errand needs a walk to a scribe and back before the answer changes.
// Long enough that PRACTICE_SKILL cannot keep taking the turn away from it.
constexpr i64 kNoSelfSafeSpellCooldownMs = 240000;   // four minutes
// One practice cast per six seconds -- the cadence the goal has always used,
// named here because the reagent target is derived FROM it (uo::spell::
// ExpectedPracticeCasts) rather than from a number picked by hand.
constexpr i64 kPracticeCastPeriodMs = 6000;
// An empty reagent pouch is BUY_SUPPLIES' problem and needs a walk to a mage
// shop and back before the answer changes -- the same reasoning, and the same
// figure, as the no-spell case above. Without it PRACTICE_SKILL takes the turn
// straight back and the errand that would fix it never runs.
constexpr i64 kNoReagentCooldownMs = 240000;   // four minutes
constexpr i32 kMaxSpellbookTrips = 3;
// Long enough that a character which cannot sell anything goes and does
// something else for a while -- hunts, gathers, crafts -- rather than asking
// again the moment the purse is still empty.
constexpr i64 kNothingToSellCooldownMs = 180000;   // three minutes
constexpr i32 kMaxTradeTrips = 3;
// "up to 50-100" (project owner). Sixty is a fighting stock: enough to see a
// character through several graveyard trips, short of hoarding wool it could
// have spun into something saleable.
constexpr i32 kBandagesWanted = 60;
constexpr i32 kMaxBandageTrips = 3;
constexpr i64 kNoBandageCooldownMs = 180000;
// When even the map is exhausted, rest a while before asking again.
constexpr i64 kExploredAllCooldownMs = 300000;
// How long a STAGNANT verdict (DecideRest: every errand blocked far too
// long) cools the goal it hands off from, and the TravelToRequiredPlace
// Wander sibling alongside it. Five minutes -- long enough that the same
// tick does not immediately re-report the fault, short enough that a
// genuinely freed-up errand is not left idle for the rest of the session.
constexpr i64 kStagnantCooldownMs = 5 * 60 * 1000;
// A pair of scissors is a few dozen coins from any tailor. Worth a walk.
constexpr i32 kScissorsMoney = 60;
constexpr i32 kMaxToolTrips = 3;
constexpr i64 kNoOreCooldownMs = 120000;
constexpr i64 kNoPetCooldownMs = 180000;
constexpr i32 kMaxTameTrips = 3;
// How long after the 0x98 name query the handler waits before it is allowed to
// call a spot empty. The name replies themselves time out in 500 ms
// (kMobilesNamesTimeoutMs, Client.cpp); the rest is settle for animals walking
// back into range -- a grazing flock drifts.
constexpr i64 kTameSettleMs = 2000;
// Sphere rolls 2-5 strokes per tame and @Fail is ordinary, so several tries are
// normal; this bounds the ones that never take.
constexpr i32 kMaxTameAttempts = 8;
// How many animals may refuse this character before the goal stands down.
// One refusal is an animal, not a verdict (a sheep that is already someone's
// pet says nothing about the next sheep); three is a spot that is not worth
// more of the session -- the same escalate-after-three rule the miner and
// the vendor chase use.
constexpr i32 kMaxTameRefusals = 3;

// WHAT A CREATURE IS LIKELY TO DO TO YOU, before it has done it.
//
// "britain graveyard has specific enemies so zombie skeletal mage etc etc"
// (project owner, 2026-08-29). The graveyard holds zombies, skeletal mages and
// spectres, and a new fencer picked the SPECTRE -- the hardest hitter of the
// three and a caster besides.
//
// The danger memory only learned by dying, so a character's first fight was
// always a coin toss. This is the prior it lacked, generated from the shard's
// own chardefs (data/revolution_creatures.tsv, 450 creatures): damage weighs
// heaviest because that is what kills a weak melee character, then armour
// because it decides whether the fight can be won at all, then hit points, and
// a flat penalty for anything that casts. The ranking it produces for the
// graveyard is the one a player would give:
//
//   Zombie 0.037 < Skeleton 0.038 < Ghoul 0.054 < Skeletal Mage 0.097
//                                               < Spectre 0.101
//
// It is only a PRIOR. Anything this character has actually learned about a
// creature overrides it, because being killed by something is better evidence
// than its stat block.
std::unordered_map<std::string, double>& SeededTaming();
std::unordered_map<std::string, double>& SeededCreatureDanger();
void LoadSeededCreatureDanger(const std::string& dataDir);
std::unordered_map<std::string, double>& SeededTaming();

inline double SeededTamingFor(const std::string& name) {
    const std::unordered_map<std::string, double>& t = SeededTaming();
    std::string key;
    for (char c : name)
        key.push_back(static_cast<char>(std::tolower(
            static_cast<unsigned char>(c))));
    const auto it = t.find(key);
    return it == t.end() ? -1.0 : it->second;
}

inline double SeededDangerFor(const std::string& name) {
    const std::unordered_map<std::string, double>& t = SeededCreatureDanger();
    std::string key;
    for (char c : name)
        key.push_back(static_cast<char>(std::tolower(
            static_cast<unsigned char>(c))));
    const auto it = t.find(key);
    return it == t.end() ? -1.0 : it->second;
}


// --- WHERE THE SHEEP ARE ----------------------------------------------------
//
// Derived from the shard's own world save, never reasoned about: the owner's
// standing rule is that spawn locations come from the save / atlas, and this
// project has broken it four times (scenario-constants-from-evidence).
// tools/pasturegen.py reads every `[WORLDCHAR c_sheep*]` out of
// runtime/save/sphereworld.scp, clusters them at 24 tiles, drops clusters
// under four animals, and writes data/revolution_pastures.tsv.
//
// Regenerate it after any spawn edit. Like the atlas, it goes stale, and a
// stale pasture table sends a tailor on a long walk to an empty field.
struct Pasture {
    i32 x = 0, y = 0;
    i32 count = 0;
    i32 radius = 0;
};
std::vector<Pasture>& Pastures();
void LoadPastures(const std::string& dataDir);

// --- WHERE THE TAMABLE ANIMALS ARE -----------------------------------------
//
// Same rule as the pastures, wider question. tools/tamablegen.py takes every
// WORLDCHAR in the save whose chardef carries a TAMING requirement
// (data/revolution_creatures.tsv, 109 of 450), clusters it per species at 15
// tiles, and writes data/revolution_tamables.tsv with the requirement on the
// row. The pasture table stays where it is -- it is the WOOL chain's data,
// sheep only, all of it in Yew, which is not a legal home city.
struct TameCluster {
    i32 x = 0, y = 0;
    i32 count = 0;
    i32 radius = 0;
    double req = 0.0;               // the chardef's TAMING requirement
    std::string label;              // "Cow x4", for the log line
};
std::vector<TameCluster>& Tamables();
void LoadTamables(const std::string& dataDir);

// A BLADED ITEM, WHICH IS NOT THE SCISSORS.
//
// Source-X shears a sheep from `case IT_WEAPON_SWORD / _AXE / _FENCE /
// _MACE_SHARP / IT_CARPENTRY_CHOP` (CClientTarg.cpp:1866-1900): the sheep is
// a CHARACTER, so pItemTarg is null, and the IT_SCISSORS case at :2135 is
// reached only with an ITEM target -- it falls straight through to
// "Scissors cannot be used on that to produce anything". This shard's
// types/type_scissors.scp hooks @TargOn_Item only, so it does not change
// that either. Scissors cut the BOLT; a blade takes the wool.
//
// The list is this shard's own itemdefs, base graphic and DUPELIST flip, for
// the bladed things a bot plausibly carries: the starter dagger, the two
// knives, the two axes a gatherer owns, and the four school weapons.
constexpr u16 kBladedGraphics[] = {
    0x0F51, 0x0F52,   // i_dagger        (t_weapon_fence)
    0x13F6, 0x13F7,   // i_knife_butcher (t_weapon_fence)
    0x0EC4, 0x0EC5,   // i_knife_skinning(t_weapon_fence)
    0x0F43, 0x0F44,   // i_hatchet       (t_weapon_axe)
    0x0F49, 0x0F4A,   // i_axe           (t_weapon_axe)
    0x13FE, 0x13FF,   // i_katana        (t_weapon_sword)
    0x1400, 0x1401,   // i_kryss         (t_weapon_fence)
    0x1440, 0x1441,   // i_cutlass       (t_weapon_sword)
    0x13B5, 0x13B6,   // i_scimitar      (t_weapon_sword)
};

// MAKE_CLOTH's own bounds. Three empty gestures, matching every other
// escalate-after-three counter here (kMaxSmeltReachFails, the vendor chase);
// four pasture trips, one per row the save-derived table holds; and a rest
// long enough that a life which cannot get wool does something else for a
// while rather than re-walking to Yew on the next tick.
constexpr i32 kMaxEmptyClothSteps = 3;
constexpr i32 kMaxClothTrips = 4;
constexpr i64 kNoClothCooldownMs = 300000;
// Four yarn make one bolt: the loom's own message table is five entries and it
// yields at ARRAY_COUNT-1 (CClientTarg.cpp:2230-2245).
constexpr i32 kYarnPerBolt = 4;
// One wool spins to three yarn (CClientTarg.cpp:2053, case IT_WOOL) and one
// bolt cuts to fifty cloth (CClientTarg.cpp:2147, ConvertBolttoCloth). These
// are the numbers that turn "20 yarn short" into "shear seven sheep".
constexpr i32 kYarnPerWool  = 3;
constexpr i32 kClothPerBolt = 50;
// HOW LONG TO STAND IN A SHORN-OUT FLOCK BEFORE LEAVING WITH WHAT IS CARRIED.
//
// A sheared sheep regrows its wool on g_Cfg.m_iWoolGrowthTime
// (CClientTarg.cpp:1890; CServerConfig.cpp:1372 reads it in MINUTES), and this
// shard sets `WoolGrowthTime=30` (runtime/sphere.ini:399). Thirty minutes is
// longer than a whole bot session, so waiting for the REGROW is never the
// plan. What this budget buys is the other thing that puts an unshorn sheep in
// range: the flock roams -- the sheep spawners carry MAXDIST=50
// (runtime/save/sphereworld.scp, i_worldgem_bit with SPAWNID=c_sheep_woolly)
// -- so a minute of standing still is often another animal. A deferral needs a
// bound; after this one the character leaves with the wool it has.
constexpr i64 kShornFlockWaitMs = 60000;
// THE SHARD'S TAILOR WORKSHOP, by the atlas's own PLACE id
// (data/revolution_atlas.txt:2116, britain_tailor_2 at 1467,1686). The wheels
// and looms placed by the M3.7 decorator stand here; TravelToService(Tailor)
// remains the fallback for a life that is nowhere near Britain, because any
// tailor shop has the stations.
constexpr const char* kTailorWorkshopPlace = "britain_tailor_2";

constexpr i64 kNoToolCooldownMs = 180000;
// Spare gold, above the profession's reserve, that makes armour shopping
// sensible rather than reckless.
constexpr i32 kArmorMoney = 400;
constexpr i64 kGearCooldownMs = 240000;
// A rest, not a write-off. RetryableFailure means THIS door said no and
// another may not -- one silent shop is not evidence about a trade.
constexpr i64 kShortRestMs = 30000;
// TRAIN_COMBAT stand-downs (early-hunting-grounds, 2026-08-31): a goal that
// ends its tick having decided NOT to fight or NOT to travel must still
// Finish(false) with an explicit Cooldown -- Finish(false) alone only stops
// counting as success, Score() still reads the goal as feasible a moment
// later (see goal-that-did-nothing-must-stand-down). kHuntStandDownMs is for
// a condition this life expects to clear on its own shortly (too hurt, too
// loaded); kNoHuntingGroundCooldownMs is for the structural one (the atlas
// has nothing reachable), so a life does not re-walk the same failed trip on
// the very next tick.
constexpr i64 kHuntStandDownMs = kShortRestMs;
constexpr i64 kNoHuntingGroundCooldownMs = 180000;
// How many times to answer "you can't reach that" by moving before
// concluding the forge itself is the problem. Three, matching the
// vendor chase: enough to get round a wall, not enough to spend a
// session on one anvil.
constexpr i32 kMaxSmeltReachFails = 3;
// A goal that used its whole time limit and finished nothing rests for two
// minutes. Long enough that something else certainly gets a turn, short enough
// that a genuinely long errand -- a walk across the map to a trainer -- can be
// resumed later in the same session.
constexpr i64 kExhaustedCooldownMs = 120000;
// HOW CLOSE IS CLOSE ENOUGH TO TRADE.
//
// One tile was too strict. Britain's shopkeepers wander a step at a time, so a
// character that insists on being adjacent re-walks every time the vendor
// shifts -- Ysolde logged "the 'mage' has moved to 1450,1618 (2 tiles) --
// walking back before buying" fifty-seven times in one session and bought
// nothing at all. Sphere refuses an out-of-reach purchase itself ("You can't
// reach the Vendor"), so the client does not need to be stricter than the
// server; it only needs to be close enough that the answer is usually yes.
//
// TWO IS THE SERVER'S NUMBER, AND THREE WAS ONE TOO MANY. Source-X answers a
// buy packet with CChar::CanTouch(vendor) (receive.cpp:752-756), and CanTouch
// refuses on `iDist > 2` -- CCharStatus.cpp:1423, where iDist is
// CPointMap::GetDist, the same Chebyshev metric as TileDist here. So a client
// that considered 3 "close enough" was guaranteed to be told no at exactly
// that distance. Aurelius proved it on the wire: he opened Kenton's shop from
// (1591,1657) with Kenton at (1588,1655) -- max(3,2) = 3 -- and the buy came
// back "You can't reach the Vendor" 1ms later, twice
// (run_gates/g_Aurelius.console.txt:411,468-470,482). This is a mirror of the
// server's own rule, not a tuning knob -- so take it from the one place that
// mirrors server rules rather than restating the number here.
constexpr i32 kVendorReach = sphere::kTouchDist;
// And a wandering vendor must not own the goal. After this many walk-backs,
// try the purchase from where we stand and let the server decide.
constexpr i32 kMaxVendorChases = 4;
// AND A TOOL THE SHARD WILL NOT LET US WIELD MUST NOT OWN THE GOAL EITHER.
// Three asks is enough to tell a slow server from a refusal; after that the
// character banks and does something else, and the gear cooldown paces the
// next attempt. (audit 2026-08-30, finding 4.)
constexpr int kMaxToolWearTries = 3;
// THE TAILORING CHAIN, END TO END. Every graphic read from this shard's own
// itemdefs and every mechanic from Source-X's source, not from generic UO:
//
//   scissors 0x0F9E on a woolly sheep (CHARDEF 0cf, body 0x00CF)
//        -> wool          CClientTarg.cpp:1878, case CREID_SHEEP
//   wool 0x0DF8 on a spinning wheel 0x1015
//        -> yarn/thread   CClientTarg.cpp:2053, case IT_WOOL
//   yarn 0x0E1D / thread 0x0FA0 on an upright loom 0x105F
//        -> cloth bolt    CClientTarg.cpp:2186, case IT_YARN/IT_THREAD
//   scissors on the bolt 0x0F95
//        -> cut cloth     CClientTarg.cpp:2147, ConvertBolttoCloth
//   scissors on cloth 0x175D
//        -> BANDAGES      CClientTarg.cpp:2151, IT_CLOTH -> ITEMID_BANDAGES1,
//                         one bandage per cloth
//
// The stations are real dynamic items and must be targeted by serial: the
// engine breaks out when pItemTarg is null, so targeting the ground beside a
// loom does nothing at all. There are 20 spinning wheels and 33 looms in the
// world -- in save/spherestatics.scp, NOT sphereworld.scp, because the M3.7
// decorator marks its placements attr_static and Source-X routes those to a
// different file.
// WHAT A CHARACTER MAY WEAR, AND HOW GOOD IT IS.
//
// "always try to wear better equipment based on your class" and "bots also
// always check for gear" (project owner, 2026-08-29).
//
// CLASS MATTERS ABSOLUTELY ON THIS SHARD, not as a penalty. revolutionuo.net's
// mining guide states that ore-smithed metal sets are Warrior-only and that
// "Bu setleri giyen karakterler buyu atamazlar" -- characters wearing them
// CANNOT CAST AT ALL (docs/REVOLUTION_EQUIPMENT_EVIDENCE.md, graded CONFIRMED).
// So metal on a caster is not a trade-off to weigh, it is the end of its
// profession. Leather is PLAUSIBLE for a caster and is allowed; cloth always.
//
// GENERATED from this shard's own itemdefs: every TYPE=t_armor,
// t_armor_leather or t_shield def carrying an ARMOR value, minus the gargish
// and elven pieces this Renaissance-era client has no art for. ARMOR and
// ReqStr are the shard's numbers, never guessed -- and ReqStr is why this
// table exists at all: a piece the character is too weak to wear is refused by
// the server, and asking repeatedly is one of the ways a goal burns a session.
constexpr ArmorPiece kArmorPieces[] = {
    {0x13BB, 25,  60, ArmorClass::Metal  },  // i_chainmail_coif
    {0x13BE, 25,  60, ArmorClass::Metal  },  // i_chainmail_leggings
    {0x13BF, 25,  60, ArmorClass::Metal  },  // i_chainmail_tunic
    {0x13C5, 13,  20, ArmorClass::Leather},  // i_leather_sleeves
    {0x13C6, 13,  20, ArmorClass::Leather},  // i_leather_gloves
    {0x13C7, 13,  20, ArmorClass::Leather},  // i_leather_gorget
    {0x13CB, 13,  20, ArmorClass::Leather},  // i_leather_leggings
    {0x13CC, 13,  25, ArmorClass::Leather},  // i_leather_tunic
    {0x13D4, 16,  25, ArmorClass::Leather},  // i_studded_sleeves
    {0x13D5, 16,  25, ArmorClass::Leather},  // i_studded_gloves
    {0x13D6, 16,  25, ArmorClass::Leather},  // i_studded_gorget
    {0x13DA, 16,  30, ArmorClass::Leather},  // i_studded_leggings
    {0x13DB, 16,  35, ArmorClass::Leather},  // i_studded_tunic
    {0x13EB, 22,  40, ArmorClass::Metal  },  // i_ringmail_gloves
    {0x13EC, 22,  40, ArmorClass::Metal  },  // i_ringmail_tunic
    {0x13EE, 22,  40, ArmorClass::Metal  },  // i_ringmail_sleeves
    {0x13F0, 22,  40, ArmorClass::Metal  },  // i_ringmail_leggings
    {0x1408, 30,  55, ArmorClass::Metal  },  // i_helm_closed
    {0x140A, 30,  45, ArmorClass::Metal  },  // i_helm_open
    {0x140C, 25,  40, ArmorClass::Metal  },  // i_bascinet
    {0x140E, 30,  55, ArmorClass::Metal  },  // i_helm_nose
    {0x1410, 30,  80, ArmorClass::Metal  },  // i_platemail_arms
    {0x1411, 30,  90, ArmorClass::Metal  },  // i_platemail_leggings
    {0x1412, 30,  80, ArmorClass::Metal  },  // i_platemail_helm
    {0x1413, 30,  45, ArmorClass::Metal  },  // i_platemail_gorget
    {0x1414, 30,  70, ArmorClass::Metal  },  // i_platemail_gloves
    {0x1415, 30,  95, ArmorClass::Metal  },  // i_platemail_chest
    {0x144E, 24,  55, ArmorClass::Metal  },  // i_bone_arms
    {0x144F, 24,  60, ArmorClass::Metal  },  // i_bone_chest
    {0x1450, 24,  55, ArmorClass::Metal  },  // i_bone_gloves
    {0x1451, 24,  20, ArmorClass::Metal  },  // i_bone_helmet
    {0x1452, 24,  55, ArmorClass::Metal  },  // i_bone_leggings
    {0x1B72, 10,  35, ArmorClass::Shield },  // i_shield_round_bronze
    {0x1B73,  7,  20, ArmorClass::Shield },  // i_shield_buckler
    {0x1B74, 12,  45, ArmorClass::Shield },  // i_shield_kite_metal
    {0x1B76, 15,  90, ArmorClass::Shield },  // i_shield_heater
    {0x1B78,  9,  20, ArmorClass::Shield },  // i_shield_kite_wood
    {0x1B7A,  8,  20, ArmorClass::Shield },  // i_shield_wood
    {0x1B7B,  9,  45, ArmorClass::Shield },  // i_shield_round_metal
    {0x1BC3, 16,  95, ArmorClass::Shield },  // i_shield_chaos
    {0x1BC4, 16,  95, ArmorClass::Shield },  // i_shield_order
    {0x1BC6, 16,  95, ArmorClass::Shield },  // i_shield_scale
    {0x1C00, 13,  20, ArmorClass::Leather},  // i_armor_female_shorts
    {0x1C02, 16,  35, ArmorClass::Leather},  // i_armor_female_studded
    {0x1C04, 30,  95, ArmorClass::Metal  },  // i_armor_female_plate
    {0x1C06, 13,  25, ArmorClass::Leather},  // i_armor_female_leather
    {0x1C08, 13,  25, ArmorClass::Leather},  // i_armor_female_skirt
    {0x1C0A, 13,  20, ArmorClass::Leather},  // i_armor_female_bustier
    {0x1C0C, 16,  35, ArmorClass::Leather},  // i_armor_female_bustier_studded
    {0x1DB9, 13,  20, ArmorClass::Leather},  // i_leather_cap
    {0x1F0B, 20,  30, ArmorClass::Metal  },  // i_helm_orc
    {0x236C, 25,  80, ArmorClass::Metal  },  // i_helm_kabuto
    {0x25E4, 15,  20, ArmorClass::Leather},  // i_armor_female_shorts_spiked
    {0x25E6, 18,  25, ArmorClass::Metal  },  // i_armor_female_harness_amazon
    {0x25E8, 20,  25, ArmorClass::Metal  },  // i_armor_female_harness_elite
    {0x2641, 28,  75, ArmorClass::Metal  },  // i_dragon_chest
    {0x2643, 28,  75, ArmorClass::Metal  },  // i_dragon_gloves
    {0x2645, 28,  75, ArmorClass::Metal  },  // i_dragon_helm
    {0x2647, 28,  75, ArmorClass::Metal  },  // i_dragon_leggings
    {0x264B, 30,  45, ArmorClass::Metal  },  // i_platemail_gorget2
    {0x2653, 30,  70, ArmorClass::Metal  },  // i_platemail_waraji_3d
    {0x2657, 28,  75, ArmorClass::Metal  },  // i_dragon_sleeves
    {0x2659, 30,  60, ArmorClass::Metal  },  // i_amazon_heavy
    {0x265B, 30,  60, ArmorClass::Metal  },  // i_amazon_medium
    {0x265D, 20,  60, ArmorClass::Metal  },  // i_amazon_light
    {0x2677, 13,  40, ArmorClass::Leather},  // i_gloves_kote1
    {0x2679, 13,  40, ArmorClass::Leather},  // i_gloves_kote2
    {0x2689, 30,  25, ArmorClass::Metal  },  // i_helm_winged
    {0x268B, 30,  40, ArmorClass::Metal  },  // i_hachimaki
    {0x268D, 30,  80, ArmorClass::Metal  },  // i_helm_kabuto_decorative
    {0x268F, 30,  80, ArmorClass::Metal  },  // i_kabuto_mempo
    {0x2691, 13,  20, ArmorClass::Leather},  // i_leather_cap2
    {0x269D, 13,  25, ArmorClass::Leather},  // i_cap_feathered
    {0x26B0, 13,  10, ArmorClass::Leather},  // i_leather_gloves_arcane
    {0x2774, 28,  50, ArmorClass::Metal  },  // i_chainmail_hatsuburi
    {0x2775, 30,  65, ArmorClass::Metal  },  // i_platemail_hatsuburi
    {0x2776, 13,  25, ArmorClass::Leather},  // i_leather_jingasa
    {0x2777, 30,  55, ArmorClass::Metal  },  // i_plate_jingasa_heavy
    {0x2778, 30,  80, ArmorClass::Metal  },  // i_platemail_kabuto_decorative
    {0x2779, 30,  50, ArmorClass::Metal  },  // i_platemail_mempo
    {0x277A, 13,  30, ArmorClass::Leather},  // i_leather_mempo
    {0x277B, 13,  40, ArmorClass::Leather},  // i_leather_do
    {0x277C, 20,  55, ArmorClass::Leather},  // i_studded_do
    {0x277D, 30,  85, ArmorClass::Metal  },  // i_platemail_do
    {0x277E, 13,  25, ArmorClass::Metal  },  // i_leather_hiro_sode
    {0x277F, 20,  30, ArmorClass::Leather},  // i_studded_hiro_sode
    {0x2780, 30,  75, ArmorClass::Metal  },  // i_platemail_hiro_sode
    {0x2781, 28,  55, ArmorClass::Metal  },  // i_plate_jingasa_light
    {0x2784, 13,  55, ArmorClass::Metal  },  // i_plate_jingasa_small
    {0x2785, 30,  70, ArmorClass::Metal  },  // i_helm_kabuto_battle
    {0x2786, 13,  20, ArmorClass::Leather},  // i_leather_suneate
    {0x2787, 20,  30, ArmorClass::Leather},  // i_studded_suneate
    {0x2788, 30,  80, ArmorClass::Metal  },  // i_platemail_suneate
    {0x2789, 30,  70, ArmorClass::Metal  },  // i_platemail_kabuto
    {0x278A, 13,  20, ArmorClass::Leather},  // i_leather_haidate
    {0x278B, 20,  30, ArmorClass::Leather},  // i_studded_haidate
    {0x278D, 30,  80, ArmorClass::Metal  },  // i_platemail_haidate
    {0x278E, 13,  10, ArmorClass::Leather},  // i_hood_ninja_leather
    {0x2790, 13,  10, ArmorClass::Leather},  // i_belt_ninja_leather
    {0x2791, 13,  10, ArmorClass::Leather},  // i_pants_ninja_leather
    {0x2792, 13,  10, ArmorClass::Leather},  // i_mitts_ninja_leather
    {0x2793, 13,  10, ArmorClass::Leather},  // i_jacket_ninja_leather
    {0x279D, 20,  30, ArmorClass::Leather},  // i_mempo_studded
    {0x2B06, 40,  70, ArmorClass::Metal  },  // i_legs_honor
    {0x2B08, 40,  65, ArmorClass::Metal  },  // i_breastplate_justice
    {0x2B0A, 40,  60, ArmorClass::Metal  },  // i_arms_compassion
    {0x2B0C, 40,  60, ArmorClass::Metal  },  // i_gauntlets_valor
    {0x2B0E, 40,  45, ArmorClass::Metal  },  // i_gorget_truth
    {0x2B10, 40,  25, ArmorClass::Metal  },  // i_helm_spirituality
    {0x2B12, 40,  10, ArmorClass::Metal  },  // i_solaretes_sacrifice
    {0x2B67, 30,  95, ArmorClass::Metal  },  // i_woodland_chest
    {0x2B69, 30,  45, ArmorClass::Metal  },  // i_woodland_gorget
    {0x2B6A, 30,  70, ArmorClass::Metal  },  // i_woodland_gauntlets
    {0x2B6B, 30,  90, ArmorClass::Metal  },  // i_woodland_leggings
    {0x2B6C, 30,  80, ArmorClass::Metal  },  // i_woodland_arms
    {0x2B6D, 30,  95, ArmorClass::Metal  },  // i_woodland_chest_female
    {0x2B6E, 30,  10, ArmorClass::Metal  },  // i_helm_circlet1
    {0x2B6F, 30,  10, ArmorClass::Metal  },  // i_helm_circlet2
    {0x2B70, 30,  10, ArmorClass::Metal  },  // i_helm_circlet3
    {0x2B71, 30,  25, ArmorClass::Metal  },  // i_helm_raven
    {0x2B72, 30,  25, ArmorClass::Metal  },  // i_helm_vulture
    {0x2B73, 30,  25, ArmorClass::Metal  },  // i_helm_winged_2
    {0x2B74, 20,  25, ArmorClass::Leather},  // i_hide_chest
    {0x2B75, 20,  15, ArmorClass::Leather},  // i_hide_gloves
    {0x2B76, 20,  15, ArmorClass::Leather},  // i_hide_gorget
    {0x2B77, 20,  20, ArmorClass::Leather},  // i_hide_arms
    {0x2B78, 20,  25, ArmorClass::Leather},  // i_hide_leggings
    {0x2B79, 20,  25, ArmorClass::Leather},  // i_hide_chest_female
    {0x317B, 13,  20, ArmorClass::Leather},  // i_leaf_chest
    {0x317C, 13,  10, ArmorClass::Leather},  // i_leaf_gloves
    {0x317D, 13,  10, ArmorClass::Leather},  // i_leaf_gorget
    {0x317E, 13,  15, ArmorClass::Leather},  // i_leaf_arms
    {0x317F, 13,  20, ArmorClass::Leather},  // i_leaf_leggings
    {0x3180, 13,  10, ArmorClass::Leather},  // i_leaf_tonlet
    {0x3181, 13,  20, ArmorClass::Leather},  // i_leaf_chest_female
    {0xA649, 20,  35, ArmorClass::Shield },  // i_shield_pirate
    {0xA7E2,  5,  10, ArmorClass::Leather},  // i_belt_demon
    {0xA831, 20,  35, ArmorClass::Shield },  // i_shield_hildebrandt
};

// i_pickaxe, layer 1, ReqStr=50 -- the same pair Professions.cpp names.
constexpr u16 kMinePickaxe[] = {0x0E85, 0x0E86};
// The four big fish this shard's water yields, and the blades that cut them.
// One whole fish becomes four cut steaks; the steaks are what a vendor buys
// and what a cook can turn into a meal.
constexpr u16 kWholeFish[] = {0x09CC, 0x09CD, 0x09CE, 0x09CF};
// How many whole fish are worth putting the pole down for. One cast yields one
// fish, so this is "cut roughly once every four casts" -- see DoFish.
constexpr i32 kFishCutBatch = 4;
constexpr u16 kBlades[]    = {0x0F51, 0x0F52, 0x13F5, 0x13F6};  // dagger, knives
// i_kindling 0x0DE1 becomes ITEMID_CAMPFIRE 0x0DE3 when lit.
constexpr u16 kKindlingGraphic = 0x0DE1;
constexpr u16 kCampfireGraphic = 0x0DE3;
// The three t_cooking itemdefs -- rolling pin, fry pan, flour sifter. Any of
// them opens the cooking skillmenu (sm_legacy_cooking.scp: "Triggered by
// DClicking a i_fry_pan, rolling pin or flour sifter") and any satisfies
// SKILLMAKE=Cooking 0.0,t_cooking on i_fish_cut_cooked. The MATERIAL cannot
// open this menu: a raw steak is IT_MEAT_RAW and double-clicking it is
// answered by EATING it (Source-X CCharUse.cpp:1862 -> Use_Eat).
constexpr u16 kCookingToolGfx[] = {0x1043, 0x097F, 0x103E};

// SMELTING, taken from the shard and not from generic UO lore.
// runtime/scripts/types/type_ore.scp is the entire mechanic, on t_ore @dclick:
//   if <cont> != <src.findlayer.21>   -> the ore must be IN THE BACKPACK
//   elif <src.mining> >= <skillmake.1.value>-100
//   if <src.isneartype t_forge 2>     -> and within TWO TILES of a forge
//     serv.newitem <tdata1>           -> which for i_ore_iron is i_ingot_iron
//   else "You must be near a forge."  (cliloc 1044265)
// There is no crafting menu anywhere in that path, which is why DoCraft --
// which knows only how to walk menus -- could never have smelted, and why
// mining filled a pack with ore that nothing would ever turn into metal.
//
// i_ore_iron is ITEMDEF 019b7 with DUPELIST=019b8,019b9,019ba (the 1/2/3/4-ore
// piles), so all four count as ore. SKILLMAKE=mining 0.0 makes the skill gate
// `mining >= -10.0` -- always true, so any miner at all can smelt iron.
constexpr u16 kIronOre[] = {0x19B7, 0x19B8, 0x19B9, 0x19BA};
// Which graphics are forges lives in Client::NearestForge -- it reads the map
// statics, and the id set is derived there from TYPE=t_forge.
// <src.isneartype t_forge 2> reads like "two tiles is fine". It is not: at a
// Chebyshev distance of exactly 2 -- standing at 2533,572 with the forge at
// 2535,571 -- the shard answered "You must be near a forge to smelt" on every
// swing. Sphere measures that distance to the object's own footprint, so the
// only reliable rule is to stand ADJACENT and then click.
constexpr i32 kForgeReach = 1;
// i_fish_cut_raw 0x097A -- four to a whole fish, and food once cooked.
constexpr u16 kFishRawSteak = 0x097A;
// Mirrors kGoldWorthCarrying in Needs.cpp: the need and the goal must agree on
// how much coin a life keeps, or one will ask for a trip the other undoes.
// The runtime half of Needs.cpp's kMaxGoldCarried: what is DEPOSITED must
// agree with what the need thought was surplus, or the trip achieves nothing.
// How many turns of a never-failing self-use skill (Meditation) before the
// planner is given another chance to choose. Small: the point is that other
// needs get looked at, not that practice is discouraged.
// How long to let a craft resolve before deciding it failed silently. Longer
// than any single craft delay on this shard, short enough not to stall a
// batch.
constexpr i64 kCraftResolveMs = 8000;
// How many times to swing at one recipe with nothing appearing before
// admitting the batch is going nowhere. Voris repeated it for a whole
// session; three is enough to ride out a slow shard and few enough to hand
// the turn on.
constexpr i32 kMaxCraftAttempts = 3;
// And how long to leave it alone afterwards -- long enough that the planner
// picks something else, short enough that a transient problem is retried.
constexpr i64 kCraftStuckCooldownMs = 120000;
constexpr i32 kSelfPracticeBeforeRethink = 6;
constexpr i32 kMaxGoldCarriedRt = 800;
constexpr i32 kGoldWorthCarryingRt = 500;
// Close enough to a mining place to call it a day at work.
// Distance to the EDGE of a mining area that still counts as being at work.
// Minoc's ore sits in resource areas of radius 20 scattered round the town, so
// a miner in Minoc is usually a short walk from one rather than standing on it.
constexpr i32 kAtOreDistance = 45;
// Close enough to actually swing: the pickaxe reaches two tiles, so anything
// beyond a few means walking in rather than hammering the ground.
constexpr i32 kMineReach = 6;
constexpr i32 kMaxMineTrips = 3;
// How far DoMine scans for genuine rock once travel says it has arrived.
// TravelToResource is satisfied at the resource area's RADIUS (Minoc's is
// r=20), so "arrived" can still be a full radius from the rock; the scan must
// out-reach that gap. 24 also covers the mine's real rects from the recorded
// centroid (a_minoc_mine_1_1 spans y474-504 around P=2558,499,
// maps/map0/map0_areas.scp:1954-1960).
constexpr i32 kMineScanRadius = 24;
// How far away a remembered productive spot may be and still be worth
// scanning from instead of from the boots. Comfortably more than the scan
// radius -- the point is to reach INSIDE the mine from its mouth -- but not
// so far that a miner walks to another county for it.
constexpr i32 kMineKnownSpotWithin = 60;
// Consecutive server refusals at the mouth (no nearby memory) before DoMine
// stops re-jittering the doorway and walks deeper into the cave instead.
// Three, same escalation point as everywhere else in this codebase.
constexpr i32 kMineRefusalsBeforeAdvance = 3;
// How many deeper-advances a single goal attempt will make before falling
// back to the ordinary give-up path. Bounds the walk so a genuinely
// rock-less cave still fails honestly rather than pacing forever.
constexpr i32 kMaxMineAdvances = 3;
// One mining attempt is 2-6 strokes (CCharSkill.cpp:1463) at DELAY=1.6s
// (skill45_mining.scp), so ~10s of silence is NORMAL. Poll the journal gently
// and only give up on a verdict well past the longest legitimate attempt.
constexpr i64 kMinePollMs = 1500;
constexpr i64 kMineResolveMs = 15000;
constexpr i32 kMaxBankShouts = 3;
// How far a spoken offer carries, in tiles.
constexpr int kTradeEarshot = 16;

// A SHOP IS A SHOP, WHEREVER YOU ARE STANDING.
//
// Every service trip passed the character's HOME CITY as a region hint, and
// that hint forces NearestPlaceWithServiceInRegion -- so a miner standing in
// Minoc who wanted a tinker was sent 440 tiles back to Vesper, because Vesper
// is where he happens to live. "it shouldnt go to vesper always, that is
// wrong" (project owner, 2026-08-29).
//
// Home is where a character LIVES. It is not a reason to walk past the shop in
// front of it. Returning nullptr makes the atlas pick the nearest place with
// the service, which is what a person does.
//
// Kept as a named function rather than deleting the argument, because there
// may yet be an errand where home genuinely matters -- a player market to be
// found at one's own bank, say -- and this is where that exception would go.
inline const char* HomeOrNearest(const std::string&) { return nullptr; }
constexpr i64 kNoBankCooldownMs = 120000;
// THE 36 ARMOUR PIECES AN ARMORER ACTUALLY STOCKS, generated from every
// SELL row in VENDOR_S_ARMORER_LEATHER / _RING / _CHAIN / _PLATE /
// _SHIELDS. Everything else with an ARMOR value is smith-crafted or
// looted, and shopping for it is a wasted trip.
constexpr u16 kSoldArmour[] = {
    0x13BB, 0x13BE, 0x13BF, 0x13C5, 0x13C6, 0x13C7, 0x13CB, 0x13CC,
    0x13EB, 0x13EC, 0x13EE, 0x13F0, 0x1408, 0x140A, 0x140C, 0x140E,
    0x1410, 0x1411, 0x1412, 0x1413, 0x1414, 0x1415, 0x1B72, 0x1B73,
    0x1B74, 0x1B76, 0x1B78, 0x1B7A, 0x1B7B, 0x1C00, 0x1C02, 0x1C06,
    0x1C08, 0x1C0A, 0x1C0C, 0x1DB9,
};

constexpr u16 kScissorsGraphic  = 0x0F9E;
constexpr u16 kWoolGraphic      = 0x0DF8;
constexpr u16 kYarnGraphic      = 0x0E1D;
constexpr u16 kThreadGraphic    = 0x0FA0;
constexpr u16 kClothBoltGraphic = 0x0F95;
constexpr u16 kClothGraphic     = 0x175D;
constexpr u16 kSheepBody        = 0x00CF;

// EVERY FACING OF A SPINNING WHEEL AND OF A LOOM.
//
// Sphere keeps ONE itemdef per station and lists its other facings in a
// DUPELIST: i_spinning_wheel is 0x1015 with
// `DUPELIST=01016,01017,01019,0101a,0101b,0101c,0101d,0101e,010a4,010a5,010a6`
// and i_loom_upright is 0x105F with `DUPELIST=01060..01066`
// (runtime/scripts/items/i_profession_tailor_tanner.scp:199, :267). The DISPID
// that reaches the client is the DUPE the decorator placed, never the base id.
//
// Measured, not assumed: Britain's tailor shop holds its wheels at 0x101C
// (1473,1689 and 1475,1689) and its looms at 0x1061/0x1062 (1473,1685 and
// 1474,1685) -- runtime/save/spherestatics.scp. Searching for the base 0x1015
// alone, Aelia stood at 1471,1690, THREE TILES from a spinning wheel, and
// logged "no spinning wheel in sight" for an entire session
// (run_gates/g_Aelia.console.txt, 22:03:30 -> 22:07:40).
constexpr u16 kSpinWheelGraphics[] = {
    0x1015, 0x1016, 0x1017, 0x1019, 0x101A, 0x101B,
    0x101C, 0x101D, 0x101E, 0x10A4, 0x10A5, 0x10A6,
};
constexpr u16 kLoomGraphics[] = {
    0x105F, 0x1060, 0x1061, 0x1062, 0x1063, 0x1064, 0x1065, 0x1066,
};

inline u32 FindStation(const Client& client, const u16* graphics, usize n,
                i32 maxDist, const std::vector<u32>& skip) {
    // NEAREST PIECE ACROSS ALL FACINGS, NOT THE FIRST FACING THAT HAS ONE.
    //
    // A loom is two pieces with two graphics. Standing at (1472,1685) with
    // the W piece 0x1061 at 1473 and the E piece 0x1062 at 1474, the old
    // loop took the first graphic in the table that matched anything and
    // handed back the FAR piece; the near piece then sat between Aelia and
    // her target, the server's CanTouch/LOS refused in silence, and three
    // `use_item_on timeout`s stood the goal down (g_Aelia.console.txt
    // 22:58:20-22:59:05, 2026-09-02). Owner: "you double click thread then
    // click loom, then it gives cloth" -- the gesture was right, the piece
    // was wrong.
    u32 best = 0;
    i32 bestD = maxDist + 1;
    for (usize i = 0; i < n; ++i) {
        const u32 found =
            client.FindWorldItemByGraphic(graphics[i], maxDist, skip);
        if (!found) continue;
        i32 x = 0, y = 0; i8 z = 0;
        if (!client.WorldItemPosition(found, &x, &y, &z)) continue;
        const i32 dx = x - client.PlayerX();
        const i32 dy = y - client.PlayerY();
        const i32 d = (dx < 0 ? -dx : dx) + (dy < 0 ? -dy : dy);
        if (d < bestD) { bestD = d; best = found; }
    }
    return best;
}
// HOW CLOSE A STATION HAS TO BE BEFORE THE CLICK IS WORTH SENDING.
//
// Two, the server's own number: a use-target is answered through
// CChar::CanTouch, which refuses on `iDist > 2` (Source-X CCharStatus.cpp:1423,
// Chebyshev). Aelia proved the other side of it on the wire -- standing at
// (1471,1691) she targeted the Britain loom at (1473,1685), Chebyshev 6, and
// got NO REPLY AT ALL, three times, each ending in `use_item_on timeout`
// (artifacts/domakecloth_shear_to_target_2026-09-02.md, defect 1).
constexpr i32 kStationReach = 2;

// HOW FAR A STATION IS LOOKED FOR. The place record for a shop is its door
// or sign, not its bench: "Britain tailor" (1467,1686) r=5 put Aelia at
// (1462,1681) with the looms at (1473,1685) -- Chebyshev 11 -- and a
// 10-tile search said "no loom in sight" for 100 s while standing in the
// shop (artifacts/needcloth_weaves_yarn_2026-09-02.md, defect a). Anything
// the client has been told about is fair to look for; ReachStation walks
// the rest. 18 is the client's update range, the furthest an item can be
// known at all.
constexpr i32 kStationSight = 18;

// HOW FULL IS "WORKED TILL CARRY CAPACITY".
//
// The gatherers' own long-standing bar, not a new number: DoGatherLogs passes
// it as GatherRequest::packFullFraction, and DoMine and DoFish test the same
// figure inline. Shearing joins them -- "they should work till carry capacity"
// (project owner, 2026-09-02) -- so all four stop at the same point and the
// bar can only be moved in one place.
constexpr double kGathererPackFullFrac = 0.95;

const std::vector<u32> kNoStationsStruckOff;
inline u32 FindSpinWheel(const Client& client, i32 maxDist,
                  const std::vector<u32>& skip = kNoStationsStruckOff) {
    return FindStation(client, kSpinWheelGraphics,
                       sizeof(kSpinWheelGraphics) / sizeof(u16), maxDist, skip);
}
inline u32 FindLoom(const Client& client, i32 maxDist,
             const std::vector<u32>& skip = kNoStationsStruckOff) {
    return FindStation(client, kLoomGraphics,
                       sizeof(kLoomGraphics) / sizeof(u16), maxDist, skip);
}

// CLOTHING A FIGHTER CAN CUT UP FOR BANDAGES.
//
// Stock Source-X has always allowed this -- CClientTarg.cpp:2154, case
// IT_CLOTHING, yielding weight/WEIGHT_UNITS bandages -- but this shard's
// types/type_scissors.scp answered every type except cloth, bolt and hide with
// RETURN 1, which tells Sphere the use was handled and stops the engine's own
// behaviour from running. t_clothing was added to that script on 2026-08-29,
// so a looted shirt is a bandage supply again.
//
// This is the cheapest bandage there is: no sheep, no wheel, no loom, and the
// garment came off a corpse the character had to kill anyway.
//
// The list is GENERATED from this shard's itemdefs, not chosen: every
// TYPE=t_clothing def weighing 6.0 or more with VALUE at or under 60, minus
// anything named robe / elven / gargish. The weight floor keeps it to garments
// worth the gesture (yield is weight in tenths, so 6.0 is six bandages) and
// the value ceiling keeps a character from shredding something it could sell
// or wear -- the Revolution special robes above all, which are the one piece
// of clothing a mage genuinely needs.
constexpr u16 kCuttableClothing[] = {
    0x1516, 0x1517, 0x152E, 0x1531, 0x1537, 0x1539, 0x153B, 0x153D,  // skirts,
    0x170B, 0x170F, 0x1713, 0x1716, 0x1717, 0x1718, 0x1719, 0x171A,  // shirts,
    0x171B, 0x1EFD, 0x1EFF, 0x1F01, 0x1F7B, 0x1FA1, 0x1FFD, 0x25EA,  // pants,
    0x25F2, 0x2649, 0x264D, 0x264F, 0x2651, 0x2655, 0x265F, 0x2661,  // hats,
    0x2663, 0x2665, 0x2667, 0x266B, 0x266D, 0x2671, 0x2673, 0x267B,  // dresses,
    0x267D, 0x267F, 0x2681, 0x2782, 0x2783, 0x2794, 0x2796, 0x27A0,  // aprons
    0x27A1,
};

constexpr u16 kSpellbookGraphic = 0x0EFA;

// --- SCROLL GRAPHICS AND SPELL NUMBERS ARE NOT THE SAME LADDER --------------
//
// The 64 magery scroll ITEMDEFs run in the CLIENT's spellbook-page order,
// which puts Reactive Armor first in circle 1; the server's SPELL_TYPE table
// puts it seventh. Every other entry agrees, so the whole mapping is
// "graphic - 0x1F2D, plus one from Weaken onward", with Reactive Armor as the
// single exception.
//
// Evidence, server/Scripts-X/items/i_magic_magery.scp read against
// server/Scripts-X/spells/spells_magery.scp:
//   01f2d i_scroll_reactive_armor    s_reactive_armor    [SPELL 7]
//   01f2e i_scroll_clumsy            s_clumsy            [SPELL 1]
//   01f2f i_scroll_create_food       s_create_food       [SPELL 2]
//   01f30 i_scroll_feeblemind        s_feeblemind        [SPELL 3]
//   01f31 i_scroll_heal              s_heal              [SPELL 4]
//   01f32 i_scroll_magic_arrow       s_magic_arrow       [SPELL 5]
//   01f33 i_scroll_night_sight       s_night_sight       [SPELL 6]
//   01f34 i_scroll_weaken            s_weaken            [SPELL 8]
//   ...   (contiguous from here)
//   01f6c i_scroll_summon_elem_water s_summon_elem_water [SPELL 64]
//
// The old range started at 0x1F2E, so a looted Reactive Armor scroll was
// invisible to the "a scroll in the pack belongs in the book" pass, and ended
// at 0x1F6D, which is not a scroll at all.
constexpr u16 kFirstScrollGraphic = 0x1F2D;   // i_scroll_reactive_armor
constexpr u16 kLastScrollGraphic  = 0x1F6C;   // i_scroll_summon_elem_water

// Which spell does this scroll teach? 0 when the graphic is not a scroll.
inline int SpellForScrollGraphic(u16 graphic) {
    if (graphic < kFirstScrollGraphic || graphic > kLastScrollGraphic) return 0;
    const int idx = static_cast<int>(graphic) - static_cast<int>(kFirstScrollGraphic);
    if (idx == 0) return 7;      // Reactive Armor, first in the art
    if (idx <= 6) return idx;    // Clumsy .. Night Sight
    return idx + 1;              // Weaken (8) onward
}
// [SPELL 2] s_create_food -- targetless, 4 mana, MAGERY 10.0 to try.
// The practice spell: nothing to target wrongly, nobody to anger.
constexpr int kSpellCreateFood = 2;
constexpr i32 kCreateFoodMana  = 4;

// The word the NPC expects after "train". Sphere matches on the skill KEY from
// skills/skill<N>_<name>.scp, not on our own label.
inline const char* SkillKey(int id) {
    switch (id) {
        // Keep these exact runtime KEY values in sync with
        // runtime/scripts/skills/skill<N>_<name>.scp.  A missing row is not a
        // harmless label issue: it turns "<name> train Parrying" into the
        // generic "<name> train", which merely prints the trainer's list and
        // never produces a price or a lesson.
        case rules::kParrying:        return "Parrying";
        case rules::kLumberjacking:   return "Lumberjacking";
        case rules::kFishing:         return "Fishing";
        case rules::kCooking:         return "Cooking";
        case rules::kCarpentry:       return "Carpentry";
        case rules::kSwordsmanship:   return "Swordsmanship";
        case rules::kTactics:         return "Tactics";
        case rules::kAnatomy:         return "Anatomy";
        case rules::kHealing:         return "Healing";
        case rules::kMining:          return "Mining";
        case rules::kBlacksmithing:   return "Blacksmithing";
        case rules::kMagery:          return "Magery";
        case rules::kMeditation:      return "Meditation";
        case rules::kAlchemy:         return "Alchemy";
        case rules::kTinkering:       return "Tinkering";
        case rules::kArmsLore:        return "ArmsLore";
        case rules::kEvaluatingIntel: return "EvaluatingIntel";
        case rules::kInscription:     return "Inscription";
        case rules::kTaming:          return "Taming";
        case rules::kAnimalLore:      return "AnimalLore";
        case rules::kVeterinary:      return "Veterinary";
        case rules::kTailoring:       return "Tailoring";
        case rules::kCartography:     return "Cartography";
        default:                      return "";
    }
}

// Which trade teaches which skill. A guildmaster teaches to 50.0 where a plain
// tradesman stops at 30.0 (c_human_guildmasters.scp:23), so the guild is
// preferred wherever one exists. Pairs are (paperdoll-title substring, the
// world model's service) so both the mobile scan and the travel layer agree.
struct TrainerFor {
    int         skillId;
    const char* trade;
    wm::Service service;
};
const TrainerFor kTrainers[] = {
    // THREE SKILLS PROFESSIONS ASK FOR AND NOBODY COULD TEACH.
    //
    // Parrying (fencer, macer, archer), Tailoring (full_crafter) and
    // Cartography (treasure_hunter) are all marked viaTrainer in the
    // catalogue and had no row here. TrainerForSkill returned null,
    // trainerTrade_ stayed EMPTY, and the goal asked
    // NearestMobileWithTrade("") -- which matches nothing, ever. Live:
    // goal_failed=TRAIN_AT_NPC reason="no '' reachable after 3 trips",
    // eight times in one six-bot run (run_m7/f6_*). The comment below this
    // table has warned about exactly this failure since the fisher hit it.
    //
    // Trades chosen from who actually HAS the skill on this shard, not from
    // generic UO: c_guild_warrior carries PARRYING={75.0 98.0}, the tailor
    // guildmaster carries TAILORING, and the mapmaker carries
    // CARTOGRAPHY={50.0 75.0} (c_human_guildmasters.scp, c_vendor_human.scp).
    {rules::kParrying,        "armorer",     wm::Service::Blacksmith},
    {rules::kTailoring,       "tailor",      wm::Service::Tailor},
    {rules::kCartography,     "mapmaker",    wm::Service::Mapmaker},
    // "swordsman" WAS A WORD NOBODY ON THIS SHARD WEARS.
    //
    // These two rows were dead for exactly the same reason the three missing
    // rows above were dead -- the goal asked NearestMobileWithTrade() for a
    // title that matches nothing -- and they were harder to spot, because a
    // wrong name looks like a right one in the table. Zero NPC chardefs across
    // runtime/scripts/npcs/*.scp carry "the swordsman"; the count is 0, next to
    // 12 for "the weaponsmith" and 6 for "the armorer".
    //
    // The warrior guildmaster is the right teacher by the owner's rule -- every
    // skill-related guildmaster teaches to 30.0 -- and it is the wrong ANSWER
    // here, because it cannot be reached. There are 7 in the world and no PLACE
    // in the atlas carries a warrior service, so TravelToService has nowhere to
    // send anyone; the nearest routable PLACE to Britain's is 47 tiles away,
    // well past scan range. The craft guildmasters work only because they stand
    // inside the shop their service already points at -- that is how Tarath
    // found Jarman and bought Carpentry. The warrior guild has no shop.
    //
    // Weaponsmiths and armorers do stand in one. Both carry the whole combat
    // set -- SWORDSMANSHIP/FENCING/MACEFIGHTING {15.0 38.0}, PARRYING/TACTICS
    // {45.0 68.0} (c_vendor_human.scp) -- both map to Service::Blacksmith,
    // which has 33 PLACEs, and 68 of them are spawned in the world save.
    // Training caps at the NPC's own roll, so a low-rolled weaponsmith teaches
    // less than a guildmaster would. A trainer that is sometimes weaker beats
    // one that is always unreachable.
    //
    // Routing guildmasters properly is real work and belongs with the atlas
    // generator, which today reads only vendor SPAWNERS and never the world
    // save's WORLDCHARs -- noted in docs/M4_OPEN_LOOSE_ENDS.md rather than
    // bodged here.
    {rules::kSwordsmanship,   "weaponsmith", wm::Service::Blacksmith},
    {rules::kTactics,         "weaponsmith", wm::Service::Blacksmith},
    {rules::kAnatomy,         "healer",      wm::Service::Healer},
    {rules::kHealing,         "healer",      wm::Service::Healer},
    {rules::kBlacksmithing,   "blacksmith",  wm::Service::Blacksmith},
    {rules::kMining,          "blacksmith",  wm::Service::Blacksmith},
    {rules::kTinkering,       "tinker",      wm::Service::Tinker},
    {rules::kArmsLore,        "blacksmith",  wm::Service::Blacksmith},
    {rules::kMagery,          "mage",        wm::Service::Mage},
    {rules::kMeditation,      "mage",        wm::Service::Mage},
    {rules::kEvaluatingIntel, "mage",        wm::Service::Mage},
    {rules::kInscription,     "scribe",      wm::Service::Scribe},
    {rules::kAlchemy,         "alchemist",   wm::Service::Alchemist},
    {rules::kTaming,          "animal",      wm::Service::Stablemaster},
    {rules::kAnimalLore,      "animal",      wm::Service::Stablemaster},
    {rules::kVeterinary,      "animal",      wm::Service::Stablemaster},
    {rules::kLumberjacking,   "carpenter",   wm::Service::Carpenter},
    // The fisher's own two. Without these NextSkillToBuy picks Fishing,
    // TrainerForSkill returns null, trainerTrade_ stays empty, and the goal
    // asks NearestMobileWithTrade("") -- burning every trip and failing.
    {rules::kFishing,         "fisher",      wm::Service::Fisherman},
    {rules::kCooking,         "cook",        wm::Service::Cook},
    {rules::kCarpentry,       "carpenter",   wm::Service::Carpenter},
};

inline const TrainerFor* TrainerForSkill(int id) {
    for (const TrainerFor& t : kTrainers) {
        if (t.skillId == id) return &t;
    }
    return nullptr;
}

// A buyer trade, as the world model names its destination. The item->trade
// half of this lives in uo::market, because it is shard vendor data that the
// need layer also has to ask about; only the trade->place mapping is here,
// where the world model is in scope.
inline wm::Service ServiceForTrade(const char* trade) {
    struct Row { const char* trade; wm::Service service; };
    static const Row kRows[] = {
        {"carpenter",   wm::Service::Carpenter},
        {"provisioner", wm::Service::Provisioner},
        {"tinker",      wm::Service::Tinker},
        {"bowyer",      wm::Service::Bowyer},
        {"blacksmith",  wm::Service::Blacksmith},
        {"jeweler",     wm::Service::Jeweler},
        {"tailor",      wm::Service::Tailor},
        {"scribe",      wm::Service::Scribe},
        {"alchemist",   wm::Service::Alchemist},
        {"mage",        wm::Service::Mage},
        {"fisher",      wm::Service::Fisherman},
        {"cook",        wm::Service::Cook},
        {"weaponsmith", wm::Service::Blacksmith},
        // THE WEAVER, who buys cotton (tm_vend.scp:896) and stands in the
        // tailor shop. Added with the NPC price floor, which is the first
        // thing to name that trade as a buyer -- without a row here it fell
        // through to GeneralVendor and the travel leg had nowhere to aim.
        // Not a guess: AtlasGenMain.cpp:579 and ClientTravel.cpp:1554 already
        // file a weaver under Service::Tailor, so this is the third copy of
        // one fact rather than a new one.
        {"weaver",      wm::Service::Tailor},
        // THE HIDE BUYERS, added with the 2026-09-02 restore of the material
        // BUY rows in tm_vend.scp. VENDOR_B_TANNER (:480-482) and
        // VENDOR_B_COBBLER (:342-344) are the live counters for i_hide and
        // i_hides_cut; without these two rows a hide row in kNpcBuyers would
        // fall through to GeneralVendor and the travel leg would aim nowhere.
        // Not new facts: ClientTravel.cpp:1555/1565 and AtlasGenMain.cpp:592/
        // :600 already file a cobbler under Tailor and a tanner under Tanner.
        {"tanner",      wm::Service::Tanner},
        {"cobbler",     wm::Service::Tailor},
    };
    for (const Row& r : kRows) {
        if (std::strcmp(r.trade, trade) == 0) return r.service;
    }
    return wm::Service::GeneralVendor;
}

// What a life gathers, as the ATLAS names it. One table, so "where is my
// work" is answered from the world model for every profession instead of
// TreeCount standing in for all of them.
//
// The atlas already files every one of these: atlasgen reads the mine and dock
// AREADEF names and measures foliage density off the client's own statics, so
// twenty docks come through tagged resources=fishing and the mines likewise.
// Nothing needed adding to the data -- only to the code that had been asking
// it one question on behalf of every character.
struct GatherKind {
    const char*      gathers;   // Profession::gathers
    wm::ResourceKind kind;
};
const GatherKind kGatherKinds[] = {
    {"logs", wm::ResourceKind::Lumber},
    {"ore",  wm::ResourceKind::Mining},
    {"fish", wm::ResourceKind::Fishing},
};

inline wm::ResourceKind ResourceKindFor(const std::string& gathers) {
    for (const GatherKind& g : kGatherKinds) {
        if (gathers == g.gathers) return g.kind;
    }
    return wm::ResourceKind::None;
}

// The two hand layers. Which one an item lands on is decided by THIS SHARD'S
// tiledata, not by generic UO: the newbie katana wears on layer 1 and the
// hatchet wears on layer 2, so a bot that hardcodes "the weapon layer" gets
// `worn on a different layer` from the server and never arms its own axe.
// Equips therefore ask for layer 0 -- "wherever this belongs" -- and the hands
// are READ as a pair.
constexpr u8 kLayerHand1 = 0x01;
constexpr u8 kLayerHand2 = 0x02;
constexpr u8 kLayerServerChooses = 0x00;

inline i32 CountAny(Client& c, const u16* list, usize n) {
    i32 total = 0;
    for (usize i = 0; i < n; ++i) total += static_cast<i32>(c.BackpackItemCount(list[i]));
    return total;
}

inline u32 FindAny(Client& c, const u16* list, usize n) {
    for (usize i = 0; i < n; ++i) {
        const u32 s = c.FindBackpackItemByGraphic(list[i]);
        if (s) return s;
    }
    return 0;
}

// SOMETHING BLADED, IN THE PACK OR IN A HAND.
//
// The pack-only variant would miss the one case that matters most: a fighter
// walking to a pasture is carrying its katana IN ITS HAND, and
// FindBackpackItemByGraphic never returns a worn item. Source-X does not care
// which -- the shear branch is reached from OnTarg_Use_Item on the item's
// TYPE, and a wielded weapon is used the same way.
inline u32 FindBlade(Client& c) {
    for (u16 g : kBladedGraphics) {
        const u32 s = c.FindItemByGraphic(g, /*includeEquipped=*/true);
        if (s) return s;
    }
    return 0;
}

// DoSmelt's ore picker (S1, docs/CRAFTER_RUN_2026_08_30.md #20). Plain FindAny
// over kIronOre returns whichever ore graphic it hits first, and ore is one
// graphic for every metal -- a coloured vein (valorite, shadow, ...) and
// plain iron are indistinguishable without the hue. Smelting a rare ore as if
// it were iron is a real loss, so this prefers hue 0 (plain iron) when both
// are in the pack and only reaches for a coloured one when there is no iron
// left to melt instead. `hueOut` reports what was actually picked either way,
// so DoSmelt can log it rather than smelt silently.
inline u32 FindIronOrePreferPlain(Client& c, u16* hueOut) {
    const u32 pack = c.BackpackSerial();
    const usize n = c.ContainerItemCount(pack);
    u32 fallback = 0;
    u16 fallbackHue = 0;
    for (usize i = 0; i < n; ++i) {
        u32 serial = 0; u16 gfx = 0, amount = 0, hue = 0;
        if (!c.ContainerItemAt(pack, i, &serial, &gfx, &amount, &hue)) continue;
        bool isOre = false;
        for (u16 g : kIronOre) {
            if (g == gfx) { isOre = true; break; }
        }
        if (!isOre) continue;
        if (hue == 0) {
            if (hueOut) *hueOut = hue;
            return serial;
        }
        if (!fallback) { fallback = serial; fallbackHue = hue; }
    }
    if (fallback && hueOut) *hueOut = fallbackHue;
    return fallback;
}

// --- HUE-RESOLVED CONTAINER LOOKUPS (S1) ----------------------------------
//
// Every one of these exists because a GRAPHIC is not an identity on this
// shard. Ore is one graphic for all sixteen metals and the iron ingot is one
// graphic for thirteen, so FindContainerItemByGraphic / BackpackItemCount ask
// a question that has no single right answer: they will happily hand back a
// valorite stack when asked for iron, or add it to the iron total. Where a
// quantity is already computed by NAME (obs.pack and obs.bank are, since S1)
// and the SERIAL is still found by graphic, the two disagree -- and the gap
// between them is a wrong item moved, sold or melted.
//
// So: find and count over the same hue-resolved name, always.

// Every item in `container` whose hue-resolved defname is `item`: the first
// one's serial, and the TOTAL amount across all of them (which is what the
// graphic-keyed BackpackItemCount used to return, minus the other metals).
inline u32 FindContainerItemByName(Client& c, u32 container, const char* item,
                            i32* amountOut) {
    if (amountOut) *amountOut = 0;
    if (!item || !container) return 0;
    u32 first = 0;
    i32 total = 0;
    const usize n = c.ContainerItemCount(container);
    for (usize i = 0; i < n; ++i) {
        u32 serial = 0; u16 gfx = 0, amount = 0, hue = 0;
        if (!c.ContainerItemAt(container, i, &serial, &gfx, &amount, &hue))
            continue;
        if (!serial) continue;
        const char* name = econ::ItemNameForGraphicAndHue(gfx, hue);
        if (!name || std::strcmp(name, item) != 0) continue;
        if (!first) first = serial;
        total += amount ? amount : 1;
    }
    if (amountOut) *amountOut = total;
    return first;
}

inline u32 FindBackpackItemByName(Client& c, const char* item, i32* amountOut) {
    return FindContainerItemByName(c, c.BackpackSerial(), item, amountOut);
}

// The hue-resolved defname of one of OUR items, found by serial in the pack.
// The vendor's 0x9E sell list carries our own serials but no hue, so this is
// how a sell offer is joined back to what the item actually is.
inline const char* PackItemNameBySerial(Client& c, u32 serial) {
    if (!serial) return nullptr;
    const u32 pack = c.BackpackSerial();
    const usize n = c.ContainerItemCount(pack);
    for (usize i = 0; i < n; ++i) {
        u32 s = 0; u16 gfx = 0, amount = 0, hue = 0;
        if (!c.ContainerItemAt(pack, i, &s, &gfx, &amount, &hue)) continue;
        if (s == serial) return econ::ItemNameForGraphicAndHue(gfx, hue);
    }
    return nullptr;
}

// IS THE OPEN SHOP WINDOW THE ONE WE ARE STANDING IN FRONT OF?
//
// It very often is not. A vendor offer persists after the goal that opened it
// ends, so the next errand inherits somebody else's stock. Ysolde walked from
// a baker to a mage, searched the BAKER's window for blank scrolls, and
// concluded "this 'mage' does not stock i_scroll_blank" -- 746 times, at 60ms
// intervals. The shop was real, the scroll was on its list
// (VENDOR_S_MAGE_SHOP: SELL=i_scroll_blank,250), and the bot was reading the
// wrong shop.
//
// Client::VendorOfferFrom() has always said whose offer it is. Nothing asked.
inline bool OfferBelongsTo(const Client& c, u32 vendor) {
    return vendor != 0 && c.VendorOfferFrom() == vendor && !c.VendorOffer().empty();
}

inline bool GraphicIsAny(u16 graphic, const u16* list, usize n) {
    for (usize i = 0; i < n; ++i) {
        if (graphic == list[i]) return true;
    }
    return false;
}

// Serial of the axe currently in a hand, or 0. The newbie kit arms a katana
// (from the Swordsmanship request), so "a hand is full" is NOT "the axe is in
// hand" -- and swinging a katana at a tree earns nothing but "The tool is out
// of charges", forever, silently.
inline u32 AxeSerialInHand(Client& c) {
    for (u8 layer : {kLayerHand1, kLayerHand2}) {
        const u16 g = c.EquippedGraphicAt(layer);
        if (GraphicIsAny(g, kHatchet, 2) || GraphicIsAny(g, kAxe, 2)) {
            return c.EquippedAtLayer(layer);
        }
    }
    return 0;
}

inline bool AxeInHand(Client& c) { return AxeSerialInHand(c) != 0; }

inline bool HandsBusy(Client& c) {
    return c.EquippedAtLayer(kLayerHand1) != 0 || c.EquippedAtLayer(kLayerHand2) != 0;
}

inline i32 TileDist(i32 ax, i32 ay, i32 bx, i32 by) {
    return std::max(ax > bx ? ax - bx : bx - ax, ay > by ? ay - by : by - ay);
}


}  // namespace runner_detail

// Defined in Gear.cpp; shared with the armour-buying path in Train.cpp.
const ArmorPiece* ArmorFor(u16 graphic);
}  // namespace uo::life
