#!/usr/bin/env python3
"""Run the controlled, fresh two-character archetype certification cohort.

The cohort uses two existing bot accounts per implemented profession.  `--reset`
removes only those selected world characters through the normal Observer
scenario, archives their local bot state, and verifies the server save before
admission.  It never edits shard save files directly.
"""
import argparse
from collections import Counter
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import time

BOT = Path(__file__).resolve().parents[1]
ROOT = BOT.parents[1]
sys.path.insert(0, str(BOT / "tools"))
import fleet_ramp  # noqa: E402
from grade_archetype import CONTRACTS  # noqa: E402

PYTHON = Path(os.environ.get("PYTHON_EXECUTABLE", sys.executable))
EXE = BOT / "build-livecheck" / "uo_client.exe"


def read_roster(path):
    return [tuple(line.split("\t")) for line in path.read_text(encoding="utf-8").splitlines()
            if line and not line.startswith("#")]


def cohort_rows():
    rows = read_roster(BOT / "run_gates" / "roster100.tsv")
    selected = []
    for family in sorted(CONTRACTS):
        if "blocked" in CONTRACTS[family]:
            continue
        members = [row for row in rows if row[2] == family][:2]
        if len(members) != 2:
            raise RuntimeError("need two roster entries for " + family)
        selected.extend(members)
    return selected


def character_serials(names):
    text = (ROOT / "runtime" / "save" / "spherechars.scp").read_text(errors="replace")
    found = {}
    for block in re.split(r"(?=^\[WORLDCHAR )", text, flags=re.M):
        serial = re.search(r"^SERIAL=([0-9A-Fa-f]+)$", block, re.M)
        name = re.search(r"^NAME=(.+)$", block, re.M)
        if serial and name and name.group(1).strip() in names:
            found[name.group(1).strip()] = serial.group(1)
    missing = sorted(names - set(found))
    if missing:
        raise RuntimeError("selected characters are absent from the server save: " + ", ".join(missing))
    return found


def prepare(directory):
    directory.mkdir(parents=True, exist_ok=True)
    rows = cohort_rows()
    (directory / "roster.tsv").write_text(
        "# name\taccount\tprofession; two fresh characters per implemented profession\n" +
        "".join("\t".join(row) + "\n" for row in rows), encoding="utf-8")
    serials = character_serials({row[0] for row in rows})
    scenario = ["# Generated by tools/certify_cohort.py; selected bot characters only.",
                "wait_world", "sleep 3000"]
    for name, _, _ in rows:
        scenario += ["say .uid.0%s.remove 1" % serials[name], "sleep 250"]
    scenario += ["sleep 1000", "say .serv.save", "sleep 20000", "logout"]
    (directory / "reset_selected_bots.txt").write_text("\n".join(scenario) + "\n", encoding="utf-8")
    (directory / "plan.json").write_text(json.dumps({"rows": rows, "serials": serials}, indent=2),
                                              encoding="utf-8")
    print("Prepared %d fresh certification lives across %d professions." %
          (len(rows), len(set(row[2] for row in rows))))


def rows_from(directory):
    path = directory / "roster.tsv"
    if not path.exists():
        raise RuntimeError("run --prepare first")
    return read_roster(path)


def reset(directory):
    rows = rows_from(directory)
    if not EXE.exists():
        raise RuntimeError("missing certified build: " + str(EXE))
    scenario = directory / "reset_selected_bots.txt"
    if not scenario.exists():
        raise RuntimeError("missing reset scenario; run --prepare again")
    passwords = fleet_ramp.account_passwords()
    admin = passwords.get("admin")
    if not admin:
        raise RuntimeError("Admin account password is unavailable")
    env = dict(os.environ)
    env["UO_BOT_PASS_CERTIFICATION_RESET"] = admin
    console = directory / "reset.console.txt"
    error = directory / "reset.err.txt"
    # A scenario path on Windows contains `C:`, which is a session-spec
    # delimiter.  Use the single-session flags so the path stays whole.
    command = [str(EXE), "--headless", "--host", "127.0.0.1", "--port", "2593",
               "--user", "Admin", "--char-name", "Observer", "--scenario", str(scenario),
               "--tag", "certification_reset", "--log", str(directory / "reset.log")]
    with console.open("wb") as out, error.open("wb") as err:
        result = subprocess.run(command, cwd=BOT, env=env, stdout=out, stderr=err, timeout=120)
    text = console.read_text(errors="replace")
    if result.returncode or "event logout_complete: acked" not in text:
        raise RuntimeError("reset scenario did not cleanly complete; see reset.console.txt")
    names = {row[0] for row in rows}
    remaining = names & set(character_serials_after_save())
    if remaining:
        raise RuntimeError("reset did not remove: " + ", ".join(sorted(remaining)))
    archive = directory / "bot_data_before_reset"
    archive.mkdir(exist_ok=True)
    for name, account, _ in rows:
        state_dir = BOT / "bot_data" / (account + "." + name)
        if state_dir.exists():
            shutil.move(str(state_dir), str(archive / state_dir.name))
    print("Reset verified; archived local state for %d selected characters." % len(rows))


def character_serials_after_save():
    text = (ROOT / "runtime" / "save" / "spherechars.scp").read_text(errors="replace")
    return re.findall(r"^NAME=(.+)$", text, re.M)


def admit(directory, minutes):
    rows = rows_from(directory)
    record = directory / "admitted.json"
    if record.exists():
        existing = json.loads(record.read_text(encoding="utf-8"))
        if len(existing) >= len(rows):
            raise RuntimeError("cohort already admitted; use --watch or choose a new directory")
        print("Resuming partial admission: %d/%d already launched." % (len(existing), len(rows)))
    fleet_ramp.admit(rows, directory, len(rows), minutes, exe=EXE)


def watch(directory):
    admitted = json.loads((directory / "admitted.json").read_text(encoding="utf-8"))
    deadline = max(row["at"] + (row["minutes"] + 20) * 60 for row in admitted.values())
    while True:
        data = fleet_ramp.status(directory, verbose=False)
        fleet_ramp.snapshot_logged_out_states(directory, admitted, data["bots"])
        done = sum(row["logged_out"] for row in data["bots"])
        print("%s %d/%d logged out" % (time.strftime("%H:%M:%S"), done, len(data["bots"])), flush=True)
        if done == len(data["bots"]) or time.time() >= deadline:
            break
        time.sleep(30)

    summary = {family: Counter(required=2) for family in CONTRACTS if "blocked" not in CONTRACTS[family]}
    report = ["# Archetype certification cohort", "",
              "| Character | Profession | Contract |", "|---|---|---|"]
    for bot in data["bots"]:
        name = bot["name"]
        cfg = admitted[name]
        after = directory / (name + ".state_after.json")
        if not bot["logged_out"] or not after.exists():
            verdict = "INCOMPLETE"
        else:
            command = [str(PYTHON), str(BOT / "tools" / "grade_archetype.py"),
                       str(directory / (name + ".console.txt")),
                       str(directory / (name + ".state_before.json")), str(after),
                       "--family", cfg["family"]]
            result = subprocess.run(command, capture_output=True, text=True, encoding="utf-8", errors="replace")
            (directory / (name + ".contract.txt")).write_text(result.stdout + result.stderr, encoding="utf-8")
            match = re.search(r"^VERDICT: (PASS|FAIL|BLOCKED)", result.stdout, re.M)
            verdict = match.group(1) if match else "ERROR"
        summary[cfg["family"]]["complete"] += verdict != "INCOMPLETE"
        summary[cfg["family"]]["passed"] += verdict == "PASS"
        report.append("| %s | %s | %s |" % (name, cfg["family"], verdict))
    report += ["", "## Certification result", "",
               "| Profession | Passed | Required | Result |", "|---|---:|---:|---|"]
    for family in sorted(summary):
        row = summary[family]
        verdict = "CERTIFIED" if row["passed"] == row["required"] else "OPEN"
        report.append("| %s | %d | %d | %s |" % (family, row["passed"], row["required"], verdict))
    (directory / "results.md").write_text("\n".join(report) + "\n", encoding="utf-8")
    print("Wrote results.md and per-character contract reports.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--directory", type=Path, required=True)
    parser.add_argument("--prepare", action="store_true")
    parser.add_argument("--reset", action="store_true")
    parser.add_argument("--admit", action="store_true")
    parser.add_argument("--watch", action="store_true")
    parser.add_argument("--minutes", type=int, default=45)
    args = parser.parse_args()
    directory = args.directory.resolve()
    if not any((args.prepare, args.reset, args.admit, args.watch)):
        parser.error("select --prepare, --reset, --admit, or --watch")
    if args.prepare:
        prepare(directory)
    if args.reset:
        reset(directory)
    if args.admit:
        admit(directory, args.minutes)
    if args.watch:
        watch(directory)


if __name__ == "__main__":
    main()
