#pragma once

#include "net/Huffman.h"
#include "net/PacketStream.h"
#include "net/Socket.h"
#include "navigation/PathPlanner.h"
#include "navigation/NavigationState.h"
#include "js/JsEngine.h"
#include "travel/Journey.h"
#include "travel/PersonalKnowledge.h"
#include "travel/WarMode.h"
#include "uo/actions.h"
#include "uo/log.h"
#include "uo/progression.h"
#include "uo/trade.h"
#include "uo/types.h"
#include "uo/world_model.h"
#include "world/SharedWorld.h"

#include <atomic>
#include <chrono>
#include <deque>
#include <functional>
#include <memory>
#include <mutex>
#include <queue>
#include <string>
#include <thread>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

namespace uo::tiledata { class TileDataLoader; }
namespace uo::map      { class Map; }
namespace uo::world    { class World; }
namespace uo::art      { class ArtLoader; }
namespace uo::texmap   { class TexmapLoader; }
namespace uo::anim     { class AnimLoader; }
namespace uo::animdata { class AnimDataLoader; }
namespace uo::animinfo { class AnimInfoLoader; }
namespace uo::hues     { class HuesLoader; }
namespace uo::render   { class Renderer; class TextRenderer; class Minimap; class RadarColors; }

namespace uo {

struct ServerEntry {
    char name[33];   // ASCII, NUL-terminated
    u16 index;
    u8  percentFull;
    u8  timezone;
    u32 ip;          // host-order IPv4
    u16 port;        // host-order
};

struct CharEntry {
    char name[31];   // ASCII, NUL-terminated; empty -> unused slot
};

namespace js { struct ClientBindings; }  // friend: live JS bindings (ClientBindings.cpp)
namespace bot { class Scenario; }        // M1 scripted action runner (bot/Scenario.h)

class Client {
public:
    struct Config {
        const char* loginHost;
        u16         loginPort;
        const char* username;
        const char* password;
        const char* version;          // e.g. "2.0.7"
        const char* logFile;          // JSON packet log path
        u32         plaintextSeed;
        u16         gamePortOverride; // 0 = trust shard's 0x8C value
        const char* gameHostOverride; // nullptr/"" = trust shard's value
        bool        sendSeed;         // false = skip the 4-byte seed
                                      // prefix on every TCP connect
        // Bot data files (M3) — loaded lazily on first `goto` command.
        const char* tiledataPath;
        const char* mapPath;
        const char* staidxPath;
        const char* staticsPath;
        const char* verdataPath;      // optional verdata.mul overlay (nullptr = none)
        // M2.5 world knowledge, generated by uo_atlasgen from the shard's own
        // data. Both are optional: without them the client still walks with
        // `goto`, it just cannot be handed a semantic destination.
        const char* atlasPath;        // revolution_atlas.txt   (nullptr = none)
        const char* navgridPath;      // revolution_navgrid.bin (nullptr = none)
        bool        legacyMovePacket; // pre-T2A 3-byte 0x02 (UO Demo)
        bool        enableKeepalive;  // false for UO Demo (no 0x73 from client)
        // --- Sphere/Source-X adapter settings (M1) ------------------------
        int         charSlot;         // slot to play (default 0)
        const char* charName;         // optional: pick the slot whose name matches
        bool        createCharIfMissing;  // send 0x00 when the account has no chars
        // Starting skills requested at character creation, as Sphere SKILL_TYPE
        // ids with values in whole points. The server clamps each to 50 and the
        // sum to 100 (CChar::InitPlayer), and its own newbie templates decide
        // the starting kit -- a character created with Magery is handed a
        // spellbook exactly as a human player's would be.
        int         createSkill[3];
        int         createSkillVal[3];
        // Starting stats for the 0x00 create packet. Source-X clamps each to 60
        // and the sum to 80 (CChar::InitPlayer). 0 means "leave the default".
        //
        // These are exposed because M3.7 proved STR is load-bearing, not
        // cosmetic: i_pickaxe carries REQSTR=50, and Revolution's tiledata gives
        // i_shovel equip layer 0 -- unwearable -- so the pickaxe is the ONLY
        // digging tool that can be equipped, and skill45_mining.scp requires
        // SRC.WEAPON. A miner therefore needs STR 50 or it cannot mine at all.
        int         createStr = 0;
        int         createDex = 0;
        int         createInt = 0;
        // Session gait. Auto (the default) means Run -- see MovementState::gait.
        // Walk/Run pin the gait for operators who need a fixed cadence.
        sphere::Gait defaultGait;
        const char* sessionTag;       // short id used in logs ("bot01"); nullptr = none
        bool        enableStdin;      // read console commands (single-session only)
        const char* scenarioPath;     // optional scripted action list (nullptr = none)
        bool        logPackets;       // write PKT hex lines to the log file
        u32         keepaliveIntervalMs;  // 0 = use the built-in default
        bool        acceptDoors;      // A* routes through door tiles, opened at runtime
        // Renderer — optional MiniFB world window (camera follows the player).
        bool        enableRenderer;   // open a window and draw the world each tick
        const char* artIdxPath;       // artidx.mul (tile bitmap index)
        const char* artPath;          // art.mul (tile bitmaps)
        const char* texIdxPath;       // texidx.mul (land texture index)
        const char* texPath;          // texmaps.mul (land textures, sloped tiles)
        const char* animIdxPath;      // anim.idx (body animation index)
        const char* animPath;         // anim.mul (body animations, still frames)
        const char* animDataPath;     // animdata.mul (animated static/dynamic art)
        const char* animInfoPath;     // animinfo.mul (mobile walk/run timing)
        const char* huesPath;         // hues.mul (object/mobile hue ramps)
        const char* radarcolPath;     // radarcol.mul (per-tile minimap colors)
        int         renderWidth;      // window framebuffer width  (<=0 -> 512)
        int         renderHeight;     // window framebuffer height (<=0 -> 384)
        int         renderScale;      // integer upscale factor    (<=0 -> 2)
        // Draw a loud magenta placeholder for any graphic/body this client
        // data set cannot resolve, instead of drawing nothing. Render-only;
        // no protocol effect. Off by default (the bots want a clean frame);
        // uo_viewer turns it on -- an observer must SEE the out-of-era object
        // rather than silently miss it. See uo/safe_graphics.h.
        bool        renderPlaceholders;
    };

    explicit Client(const Config& cfg);
    ~Client();

    // Blocking convenience wrapper: Start(), then Tick() until the session
    // ends. Equivalent to what a single-client process wants.
    int Run();

    // Non-blocking lifecycle, for hosting several sessions in one thread.
    //   Start()    connect + seed + 0x80 + load the scenario. false on failure.
    //   Tick(ms)   one pump iteration; waits up to `waitMs` for socket data.
    //   Finished() the session has ended (disconnected or failed).
    //   ExitCode() 0 on a clean session, non-zero on failure.
    bool Start();
    void Tick(int waitMs);
    bool Finished() const { return finished_; }
    int  ExitCode() const { return exitCode_; }
    const char* SessionTag() const { return sessionTag_; }

    // -----------------------------------------------------------------
    // Player action API — the adapter boundary.
    //
    // Everything above this line is protocol plumbing; everything that
    // drives the character (an M1 scenario today, a bot brain later) uses
    // only these calls and never touches packets, sockets or wire state.
    // Each action is what a human player can do through the UO client:
    // the server stays authoritative and may refuse any of them.
    // -----------------------------------------------------------------
    bool IsInWorld() const { return state_ == State::InWorld; }
    u32  PlayerSerial() const { return playerSerial_; }
    i32  PlayerX() const { return playerX_; }
    i32  PlayerY() const { return playerY_; }
    i8   PlayerZ() const { return playerZ_; }
    u32  BackpackSerial() const { return PlayerEquipSerialAt(0x15); }  // layer 21 = backpack
    bool BackpackContentsKnown() const { return backpackContentsKnown_; }

    // Queue `count` single steps in `dir` (0=N, 1=NE, ... 7=NW). Steps are
    // paced and sent one at a time, each waiting for the server's 0x22/0x21.
    void ActionWalk(u8 dir, int count);
    bool WalkQueueBusy() const;          // steps still queued or in flight

    // Session gait -- the standing order every movement source inherits.
    // Auto (the default) means run; individual steps can still ask for Walk
    // (see BotStepGait). Scenarios override it with the `gait` verb.
    sphere::Gait MovementGait() const { return nav_.movement.gait; }
    void SetMovementGait(sphere::Gait g);
    // Ask the A* planner for a route to (x, y) and walk it. The planner only
    // produces desired steps; every one of them is still submitted by the
    // movement controller (SubmitStep), so pacing, sequencing, the
    // outstanding-step limit and reject handling apply exactly as they do to
    // a scripted walk.
    // `hasZ` pins the destination FLOOR. A two-storey shop is two different
    // places at one (x, y): the Britain mage stands at ground level and the
    // upper gallery above him is a different room, and a bot that "arrived"
    // on the wrong one is out of earshot of the vendor it walked across the
    // continent to talk to.
    void ActionGoto(i32 x, i32 y, bool hasZ = false, i8 z = 0);
    // Walk to a mobile the server has told us about. NPCs wander, so a
    // scenario cannot assume a fixed tile for a vendor or a banker.
    bool ActionGotoMobile(u32 serial, int stopWithin = 1);
    bool MobilePosition(u32 serial, i32* x, i32* y, i8* z = nullptr) const;
    bool GotoBusy();                     // planning or walking a route
    bool GotoSucceeded() const { return gotoArrived_; }

    // -----------------------------------------------------------------
    // M2 player action primitives.
    //
    // Each expresses player INTENT; the packet layout lives underneath. They
    // start an asynchronous action and return immediately -- completion is
    // server-confirmed, observed through packets, and reported through
    // ActionResult(). A scenario waits with ActionBusy() and then branches on
    // the result, so "the packet was sent" and "the server did it" are never
    // confused. Every action has a deadline and fails cleanly on timeout.
    //
    // Only one deliberate action is in flight at a time (a player has one pair
    // of hands). Movement is deliberately NOT an action: it keeps its own
    // controller, so a bot can walk while an action is outstanding.
    // -----------------------------------------------------------------
    bool         ActionBusy() const { return action_.Active(); }
    act::Result  ActionResult() const { return action_.result; }
    act::Kind    ActionKind() const { return action_.kind; }
    const act::Action& CurrentAction() const { return action_; }

    // Objects and containers
    void ActionUseObject(u32 serial);           // double-click anything
    void ActionOpenContainer(u32 serial);       // double-click, expect contents

    // Inventory
    void ActionMoveItem(u32 serial, u16 amount, u32 destContainer);
    void ActionDropGround(u32 serial, u16 amount, i32 x, i32 y, i8 z);

    // Equipment
    void ActionEquip(u32 serial, u8 layer);
    void ActionUnequip(u32 serial);             // back into the backpack

    // Targeting (answering a cursor the server armed)
    bool ActionTargetObject(u32 serial);
    bool ActionTargetGround(i32 x, i32 y, i8 z);
    // Answer a cursor with a STATIC tile, naming its graphic. Required for
    // anything the server identifies through CanTouchStatic(&pt, id, ...) --
    // chopping a tree is the case that forced this: trees are statics, a plain
    // ground reply carries graphic 0, and the shard answers "It appears immune
    // to your blow" because it cannot see a tree at the point.
    bool ActionTargetStatic(i32 x, i32 y, i8 z, u16 graphic);
    bool ActionCancelTarget();
    bool TargetActive() const { return target_.Active(); }
    u32  TargetGeneration() const { return target_.Generation(); }
    u8   TargetSubtype() const { return target_.Current().subtype; }

    // Skills and magery
    void ActionUseSkill(int skillId, u32 targetSerial = 0);
    void ActionCastSpell(int spellId, u32 targetSerial = 0);
    // Cast the spell carried by a scroll. Sphere treats a scroll as the caster
    // (src/game/clients/CClientUse.cpp:350-371), so this is the route a player
    // has when they own no spellbook. Confirmed by the scroll being consumed.
    void ActionCastScroll(u32 scrollSerial, u32 targetSerial = 0);

    // Combat
    void ActionAttack(u32 serial);
    void ActionWarMode(bool on);

    // Healing
    void ActionUseBandage(u32 bandageSerial, u32 targetSerial);

    // One row of a vendor offer, joined from the 0x3C stock contents and the
    // 0x74 price/name list. Plain data: the scenario picks what to buy.
    struct VendorItem { u32 serial; u16 graphic; u16 amount; u32 price; u8 layer; std::string name; };

    // Banking and vendors
    void ActionOpenBank(u32 bankerSerial, const char* phrase = "bank");
    // Ask a vendor to show its wares. Sphere opens the shop from SPEECH, not
    // from a double-click, so this says the word a player would say.
    void ActionVendorOpen(u32 vendorSerial, const char* phrase = "buy");
    // NPC teaching (Sphere's stock Teaching system; see the .cpp for the
    // runtime's NPCTrainPercent / NPCTrainMax / NPCTrainCost values).
    void ActionNpcTrain(u32 npcSerial, const char* skillKey);
    void ActionNpcGive(u32 mobileSerial, u32 itemSerial, u16 amount);
    void ActionVendorBuy(u32 vendorSerial, u32 itemSerial, u16 qty);
    // Ask a vendor what it will buy. Sphere answers with 0x9E, which -- unlike
    // the buy flow -- carries the item serials itself.
    void ActionVendorSellOpen(u32 vendorSerial, const char* phrase = "sell");
    void ActionVendorSell(u32 vendorSerial, u32 itemSerial, u16 qty);
    const std::vector<VendorItem>& VendorSellOffer() const { return vendorSellOffer_; }
    const std::vector<VendorItem>& VendorOffer() const { return vendorOffer_; }
    // Player vitals, read straight from the server's own status packets.
    i32  PlayerHp() const;
    i32  PlayerHpMax() const;
    u32  VendorOfferFrom() const { return vendorOfferVendor_; }

    // Life state (server-driven only)
    act::LifeState Life() const { return life_; }
    bool IsDead() const { return life_ == act::LifeState::Dead; }
    void ActionResurrectAccept();               // answer a 0x2C resurrect menu

    // Introspection used by scenarios and tests
    // Nearest cached mobile (server-driven; never invented). maxDist 0 = any.
    u32  NearestMobile(int maxDist) const;
    u32  NearestMobileNamed(const char* needle) const;
    // Nearest mobile whose paperdoll TRADE is exactly `trade` -- the text
    // after the last " the " in "<name>, the <trade>". A substring match is
    // not good enough here: "the mage guildmaster" contains "the mage", and
    // the guildmaster keeps no shop, so a bot shopping for reagents would
    // stand in front of him saying "buy" to no answer.
    u32  NearestMobileWithTrade(const char* trade) const;
    // "<name> <phrase>" when the mobile's paperdoll name is known, so exactly
    // one NPC in earshot answers (Source-X CClientEvent.cpp:1962).
    std::string AddressMobile(u32 serial, const char* phrase) const;
    // Nearest mobile whose body graphic matches. Body ids come from the
    // server's own 0x78, and a creature's CHARDEF id IS its body, so a
    // scenario can name exactly which creature it means instead of taking
    // whatever happens to be closest.
    u32  NearestMobileWithBody(u16 body, int maxDist) const;
    u32  FindBackpackItemByGraphic(u16 graphic) const;
    // The nearest WORLD item with this graphic, or 0. Needed because a craft
    // STATION is a dynamic world item and must be targeted by SERIAL: Source-X
    // resolves a use-target with uid.ObjFind() (CClientEvent.cpp:2481), so a
    // GROUND target yields pItemTarg == nullptr and the IT_WOOL / IT_YARN /
    // IT_THREAD cases in OnTarg_Use_Item silently do nothing. Targeting the
    // ground beside a spinning wheel answers "You can't think of a way to use
    // that item."
    u32  FindWorldItemByGraphic(u16 graphic, i32 maxDist = 8) const;
    // The same search across worn gear as well. A newbie kit hands out tools
    // the shard then EQUIPS -- a fishing pole is a weapon as far as Sphere is
    // concerned (i_fishing_pole has SKILL=Fencing) -- so "the pole in my pack"
    // finds nothing while the character is holding it.
    u32  FindItemByGraphic(u16 graphic, bool includeEquipped) const;
    u32  BackpackItemCount(u16 graphic) const;
    i32  PlayerMana() const;
    i32  PlayerGold() const;

    // -----------------------------------------------------------------
    // Skills and stats, as the SERVER reports them (0x3A / 0x11).
    //
    // Values are in tenths, which is how Sphere stores and sends them:
    // 500 is 50.0. Nothing here is ever written locally -- a skill only
    // changes when the shard says it did, which is the whole point of
    // training being real.
    //
    // The skill id on the wire is 1-based in the full-list form (a 0 id
    // terminates the list), so `SkillIndex` is id - 1 and is what the
    // Scripts-X `[SKILL n]` sections and the client's skills.mul use.
    // -----------------------------------------------------------------
    struct SkillReport {
        u16 wireId;        // as sent by 0x3A
        u16 index;         // wireId - 1: the [SKILL n] number
        u16 valueTenths;   // current, including item/stat modifiers
        u16 baseTenths;    // the trained value -- what training moves
        u16 capTenths;     // 0 when the server did not send one
        u8  lock;
    };
    usize PlayerSkillCount() const { return player_.skills.size(); }
    bool  PlayerSkillInfo(u16 index, SkillReport* out) const;
    // Trained value of a skill in tenths; -1 when the server has not told us.
    i32   PlayerSkillBase(u16 index) const;
    void  PlayerSkillsAll(std::vector<SkillReport>& out) const;
    // Sum of every trained skill, in tenths -- the number the shard's
    // SKILLSUM cap is measured against.
    u32   PlayerSkillSum() const;

    i32  PlayerStr() const { return player_.strength; }
    i32  PlayerDex() const { return player_.dexterity; }
    i32  PlayerInt() const { return player_.intelligence; }
    i32  PlayerStatSum() const;
    i32  PlayerStatCap() const { return player_.statsCap; }
    i32  PlayerManaMax() const { return player_.manaMax; }
    i32  PlayerWeight() const { return player_.weight; }
    i32  PlayerMaxWeight() const { return player_.maxWeight; }
    u32  EquippedAtLayer(u8 layer) const { return PlayerEquipSerialAt(layer); }
    bool PlayerIsMounted() const;
    void ActionDismount();
    bool ContainerKnown(u32 serial) const;
    u32  BankContainer() const { return bankContainer_; }

    // Ask the server for the names of nearby mobiles (0x98 per mobile). NPC
    // names carry their trade ("<name> the provisioner"), which is the only
    // way a client can tell one vendor from another.
    void ActionScanMobiles();

    // Ask the shard for this character's skill list (0x34 subtype 5). A client
    // is not told its skills until it asks, exactly as the real client only
    // learns them when the player opens the skills gump.
    void ActionRequestSkills();

    // -----------------------------------------------------------------
    // Secure player-to-player trade (M3).
    //
    // Opening one means dropping an item on the other player, which is the
    // only way a 2.0.x client has. Everything after that is 0x6F and the
    // ordinary container packets. See include/uo/trade.h for the protocol
    // notes and for the one rule this client enforces that the server does
    // not.
    // -----------------------------------------------------------------
    void ActionTradeStart(u32 partnerSerial, u32 itemSerial);
    void ActionTradeOffer(u32 itemSerial, u16 amount = 1);
    bool ActionTradeAccept(bool accept);
    bool ActionTradeCancel();
    const trade::TradeState& Trade() const { return trade_; }

    // -----------------------------------------------------------------
    // M2.5 semantic travel.
    //
    // The whole point of this block is that nothing above it names a
    // coordinate. A bot brain says what it needs -- a bank, a healer, the
    // Britain region, the mobile it can see -- and the travel layer resolves
    // that against the shared world atlas, plans a route, and hands each leg
    // to the same M1.5 tile A* that `goto` uses. Coordinates still exist;
    // they just stop being the interface.
    //
    // Each call starts a journey and returns false only when the destination
    // cannot be RESOLVED (no such place, no world knowledge loaded). Whether
    // the journey succeeds is answered later by TravelBusy()/TravelSucceeded(),
    // exactly like the M2 actions: "we set off" and "we arrived" are different
    // facts and are never conflated.
    // -----------------------------------------------------------------
    bool TravelToPoint(i32 x, i32 y, i32 arriveRadius, const char* label);
    bool TravelToPlace(const char* nameOrId);
    bool TravelToRegion(const char* nameOrId);
    // `regionHint` narrows the search to one region ("the bank in Yew");
    // nullptr means the nearest one anywhere.
    bool TravelToService(wm::Service s, const char* regionHint = nullptr);
    bool TravelToResource(wm::ResourceKind r);
    // Walk to a mobile the server has shown us. NPCs wander, so the goal is
    // re-aimed at the live position as we close in.
    bool TravelToEntity(u32 serial, i32 within = 2);
    // Where this character died, if it has. False when it has not.
    bool TravelToLastCorpse();
    bool ReturnHome();

    // Whether this character will plan routes through public moongates. A
    // gate that worldgen never placed cannot be used, so this stays off until
    // the caller knows otherwise.
    void SetUseMoongates(bool on) { travelUseMoongates_ = on; }
    bool UseMoongates() const { return travelUseMoongates_; }

    bool TravelBusy() const { return journey_.Active(); }
    bool TravelSucceeded() const { return travelSucceeded_; }
    const char* TravelFailureText() const { return travelFailure_.c_str(); }
    void TravelAbort(const char* why);
    const char* TravelPhaseName() const;

    // World knowledge, for scenarios/tests that want to assert on it.
    const wm::Region* CurrentRegion() const;
    const wm::Place*  NearestServicePlace(wm::Service s) const;
    const wm::Place*  NearestResourcePlace(wm::ResourceKind r) const;
    // True when the character is standing inside the named place's own
    // interaction radius -- the honest "did we arrive" question, since a
    // vendor's spawner range is what decides how close is close enough.
    bool WithinPlace(const char* nameOrId) const;
    // True when the character's tile falls inside the named region's own
    // rectangles. Deliberately NOT a group match: Scripts-X files Monster
    // Valley under GROUP=Yew even though it is four hundred tiles away, so a
    // group test answers "am I in Yew?" with a cheerful yes from the wrong
    // side of the map.
    bool WithinRegion(const char* nameOrId) const;
    bool WorldKnowledgeReady();
    const char* WorldKnowledgeError();

    // Per-character knowledge. Session-owned: never shared, never static.
    travel::PersonalKnowledge&       Knowledge()       { return knowledge_; }
    const travel::PersonalKnowledge& Knowledge() const { return knowledge_; }

    // -----------------------------------------------------------------
    // War / peace.
    //
    // War mode is the server's state, learned from 0x72 and changed by sending
    // 0x72. EnsurePeaceMode() is what every peaceful intent calls; the
    // watchdog additionally drops a stale war mode on its own so a bot cannot
    // walk into the next town with its weapon out.
    // -----------------------------------------------------------------
    void EnterWarMode();
    void ExitWarMode();
    void EnsurePeaceMode();
    bool WarModeOn() const { return playerWarMode_; }
    const travel::WarModeWatchdog& WarWatchdog() const { return war_; }

    // Answer a generic gump (0xB0) the server opened -- the public moongate's
    // destination list is one. `optionIndex` is a radio/checkbox id from
    // GumpOptions(); `button` is the gump's own button id.
    // One selectable thing in an open gump. `button` distinguishes a press
    // (which submits) from a radio/checkbox (which is a choice submitted with
    // a press) -- the moongate gump needs one of each: tick a destination,
    // then press OKAY.
    struct GumpOption { u32 id; bool button; std::string label; };
    bool GumpActive() const { return gump_.active; }
    const std::vector<GumpOption>& GumpOptions() const { return gump_.options; }
    u32  GumpContext() const { return gump_.context; }
    bool AnswerGump(u32 button, u32 optionId);
    bool CloseGump();
    // Answer a 0x7C MENU by 1-based option index (0 cancels). Sphere's craft
    // menus are menus, not gumps -- the Carpentry menu arrives as
    // `[0x7C] menu=690 "Carpentry"` and is answered with 0x7D -- so AnswerGump
    // cannot reach them. Public face of the private AnswerDialog.
    bool ActionMenuChoose(u16 index);

    void ActionSay(const char* text);    // 0x03 ascii speech
    void ActionOpenBackpack();           // 0x06 double-click the worn backpack
    void ActionLogout();                 // 0xD1 + socket close

    // -----------------------------------------------------------------
    // Read-only render inspection (uo_viewer).
    //
    // These expose what the renderer already drew. They send nothing, change
    // no session state and have no protocol effect whatsoever -- they exist so
    // the observer client can prove it produced a frame (dump it to PNG) and
    // can tell whether its window is still up.
    // -----------------------------------------------------------------
    bool RenderWindowOpen() const { return renderWindowOpen_; }
    int  RenderWidth() const;
    int  RenderHeight() const;
    const u16* RenderFrame() const;                 // nullptr before frame 1
    bool SaveRenderFramePng(const char* path) const;

private:
    // Live JS Player getters read private player state directly (no snapshot).
    // Defined in src/js/ClientBindings.cpp; keeps quickjs.h out of this header.
    friend struct js::ClientBindings;
    enum class State : u8 {
        Disconnected,
        LoginHandshake,
        AwaitingServerList,
        AwaitingGameServer,
        ConnectingToGameServer,
        GameHandshake,
        AwaitingCharacterList,
        AwaitingLoginConfirm,
        InWorld,
        Failed,
    };

    // --- main pump --------------------------------------------------------
    bool ConnectAndSendSeed(const char* host, u16 port);
    // (the old PumpUntilDisconnected loop is now Run() + Tick())
    void Dispatch(const u8* data, usize size);

    // --- per-session logging ----------------------------------------------
    // These deliberately shadow the uo::Log* free functions. Inside any Client
    // member function an unqualified LogInfo(...) therefore resolves here and
    // is written through this session's own Logger -- tagged with the session
    // id and routed to this session's log file. Non-member code keeps using
    // the process-wide logger.
    void LogInfo (const char* fmt, ...) const;
    void LogWarn (const char* fmt, ...) const;
    void LogError(const char* fmt, ...) const;
    void LogEvent(const char* kind, const char* detail) const;
    void LogPacket(Direction dir, const u8* data, usize size,
                   const char* note = nullptr) const;

    // --- outbound ---------------------------------------------------------
    bool Send(const u8* data, usize size, const char* note = nullptr);
    // Packet log with the password field masked (0x80 / 0x91).
    void LogPacketRedacted(Direction dir, const u8* data, usize size,
                           const char* note);

    // --- inbound handlers (1:1 with dispatcher switch cases we care about)
    void OnServerList         (const u8* data, usize size);
    void OnLegacyCharList     (const u8* data, usize size);  // 0x81 (UO Demo)
    void OnConnectToGameServer(const u8* data, usize size);
    void OnCharacterList      (const u8* data, usize size);
    void OnLoginConfirm       (const u8* data, usize size);
    void OnLoginComplete      (const u8* data, usize size);
    void OnLoginDenied        (const u8* data, usize size);
    void OnClientVersionQuery (const u8* data, usize size);
    void OnFeatures           (const u8* data, usize size);
    void OnViewRange          (const u8* data, usize size);
    void OnPing               (const u8* data, usize size);
    void OnStats              (const u8* data, usize size);
    void OnMobileHp           (const u8* data, usize size);  // 0xA1
    void OnMobileMana         (const u8* data, usize size);  // 0xA2
    void OnMobileStamina      (const u8* data, usize size);  // 0xA3
    void OnMobileAttributes   (const u8* data, usize size);  // 0x2D
    void OnSkills             (const u8* data, usize size);  // 0x3A
    void OnObjectInfo         (const u8* data, usize size);  // 0x1A
    void OnDeleteObject       (const u8* data, usize size);  // 0x1D
    void OnDrawContainer      (const u8* data, usize size);  // 0x24
    void OnAddItemToContainer (const u8* data, usize size);  // 0x25
    void OnContainerContents  (const u8* data, usize size);  // 0x3C
    void OnVendorShopData     (const u8* data, usize size);  // 0x74 buy-window prices
    void OnVendorOfferAccept  (const u8* data, usize size);  // 0x3B vendor transaction closed
    void OnOpenPaperdoll      (const u8* data, usize size);  // 0x88 paperdoll (carries title)
    void OnOverallLightLevel  (const u8* data, usize size);  // 0x4F
    void OnPersonalLightLevel (const u8* data, usize size);  // 0x4E
    void OnMobileMove         (const u8* data, usize size);  // 0x77
    void OnMobileIncoming     (const u8* data, usize size);  // 0x78
    void OnSwing              (const u8* data, usize size);  // 0x2F fight/swing
    void OnEquipItem          (const u8* data, usize size);  // 0x2E
    void OnCharacterAnimation (const u8* data, usize size);  // 0x6E
    void OnWarMode            (const u8* data, usize size);  // 0x72
    void OnResurrectionMenu   (const u8* data, usize size);  // 0x2C
    void OnOpenDialog         (const u8* data, usize size);  // 0x7C menu/dialog
    void OnDeathAnimation     (const u8* data, usize size);  // 0xAF
    void OnMobName            (const u8* data, usize size);  // 0x98
    void OnTargetCursor       (const u8* data, usize size);  // 0x6C
    void OnAsciiMessage       (const u8* data, usize size);
    void OnUnicodeMessage     (const u8* data, usize size);
    void OnUnknown            (const u8* data, usize size);
    void OnLogoutAck          (const u8* data, usize size);  // 0xD1
    void OnDragCancel         (const u8* data, usize size);  // 0x27
    void OnAttackAck          (const u8* data, usize size);  // 0xAA
    void OnVendorSellList     (const u8* data, usize size);  // 0x9E
    void RememberJournalMessage(u32 sourceSerial, u16 sourceBody, u8 type,
                                u16 hue, u16 font, const char* speaker,
                                const char* text);

    // M3 — movement
    void OnDrawGamePlayer     (const u8* data, usize size);  // 0x20
    void OnMoveReject         (const u8* data, usize size);  // 0x21
    void OnMoveAck            (const u8* data, usize size);  // 0x22

    // --- console UI -------------------------------------------------------
    int  PromptServerSelection();
    int  PromptCharacterSelection();

    // --- stdin reader thread (in-world speech + bot commands) -------------
    void StartStdinThread();
    void StopStdinThread();
    void PumpStdinCommand();
    void HandleStdinLine(const char* line);
    void SayAscii(const char* text);   // send 0x03 ascii speech (console + JS Player.say)
    void SendAttack(u32 serial);       // 0x05 attack request (JS Player.attack)
    void SendDoubleClick(u32 serial);  // 0x06 raw double-click by serial (JS Player.doubleClick);
                                       // double-clicking an NPC opens its paperdoll (-> 0x88 title)
    void SendTakeToBackpack(u32 serial, u16 qty); // 0x07+0x08 lift item from any open container -> backpack (JS Player.take)
    void SendSkillsRequest();          // 0x34 subtype 5 -> full 0x3A skill list
    void SendStatusRequest(u32 serial); // 0x34 status query (JS Player.requestStatus);
                                        // server then pushes 0xA1 HP updates for it
    void SetWarMode(bool on);          // 0x72 war-mode toggle (JS Player.warMode)
    void SendResurrectChoice(u8 choice); // 0x2C resurrect menu reply (JS Player.resurrect)
    bool PlayerIsGhost() const {       // dead == ghost body (Mobile_IsGhostForm @0x4c6930)
        return playerBody_ == 0x192 || playerBody_ == 0x193;
    }
    // 0x7C Open Dialog/Menu (e.g. the healer resurrect prompt). The whole dialog
    // is parsed into activeDialog_ and forwarded to JS as the `dialog` event.
    struct DialogOption {
        u16 model = 0;       // option's display model (0 for a text-only list)
        u16 hue = 0;
        std::string text;    // option label as sent (e.g. "YES - You choose...")
    };
    struct ActiveDialog {
        bool active = false;
        u32  id = 0;         // dialogSerial (echoed back in 0x7D)
        u16  menuId = 0;
        std::string question;
        std::vector<DialogOption> options;   // 1-based on the wire; [0] = option 1
    };
    const ActiveDialog& Dialog() const { return activeDialog_; }
    void SendDialogResponse(u32 id, u16 menuId, u16 index, u16 model, u16 hue); // 0x7D
    bool AnswerDialog(u16 index);      // answer activeDialog_ by 1-based index (0 = cancel)
    void OpenBackpack();               // 0x06 double-click the worn backpack
    void TryOpenBackpackOnLogin();     // open it once, as soon as its serial is known

    // --- Sphere adapter (M1) ---------------------------------------------
    void SendGameLogin();              // 0x91 on the current socket
    void SendCreateCharacter();        // 0x00 create-character request
    // --- movement: the single submission path ----------------------------
    // Outcome of offering one step to the movement controller.
    enum class StepSubmit : u8 {
        Sent,       // a real step went out; the caller should consume it
        Turned,     // a turn went out; offer the same direction again
        Throttled,  // too soon (pacing); retry later
        InFlight,   // outstanding-step limit reached; retry later
        Failed,     // the send itself failed
    };
    // The ONLY place a 0x02 is built and sent. Owns the sequence, the pacing,
    // the outstanding-step limit, the gait resolution and the local prediction.
    // `gait` is per step: Auto defers to the session gait, Walk/Run pin this
    // one step (final approach, doorways, shoves).
    StepSubmit SubmitStep(u8 dir, sphere::Gait gait, const char* source);
    // True if a step submitted with `gait` right now would carry the 0x80 bit.
    bool GaitResolvesToRun(sphere::Gait gait) const;

    void PumpDirectSteps();            // drive ActionWalk's queue (no A*)
    void OnStepRejected(u8 dir);       // resync bookkeeping for a rejected step

    // --- M2 action plumbing ------------------------------------------------
    void BeginAction(act::Kind kind, i64 timeoutMs);
    void FinishAction(act::Result r, const char* why);
    void ActionTick();                 // deadline sweep, one per client tick
    void OnTargetArmedForAction();     // a 0x6C arrived while an action waits
    // Confirmation hooks, called from the packet handlers.
    void ActionOnContainerOpened(u32 serial, u16 gumpId);
    void ActionOnContainerContents(u32 container, u16 count);
    void ActionOnItemInContainer(u32 item, u32 container);
    void ActionOnItemEquipped(u32 mobile, u32 item, u8 layer);
    void ActionOnItemWorld(u32 item, i32 x, i32 y, i8 z);
    void ActionOnDragCancel(u8 reason);
    void ActionOnSysMessage(const char* text, u32 sourceSerial, u8 type);
    void ActionOnManaChanged(i32 mana);
    void ActionOnGoldChanged(i32 gold);
    void ActionOnObjectDeleted(u32 serial);
    void ActionOnBodyChange(u16 body);
    void ActionOnVendorOffer(u32 vendorSerial);
    void ActionOnAttackAck(u32 serial);
    // Lift + drop, the two halves of every UO item move.
    bool SendLift(u32 serial, u16 amount);
    void SendDropToContainer(u32 serial, u32 container);
    void SendDropToGround(u32 serial, i32 x, i32 y, i8 z);
    void PumpKeepalive();              // 0x73 while in world
    void ReportUnframeableStream(const char* err);  // log + end session safely
    void PrintNearbyMobiles();
    void FlushPendingMobilesList();
    const char* MobileName(u32 serial) const;
    u32 ResolveFollowSerialByName(const char* name) const;
    void RememberMobileName(u32 serial, const char* name);
    bool ParseSerial(const char* text, u32* out) const;
    bool ParseDistance(const char* text, u32* out) const;

    // --- M3 bot -----------------------------------------------------------
    bool EnsureWorldLoaded();
    // Show a chopped/depleted tree at (x,y,z) as a stump in the world view for
    // `ttlMs` (<=0 uses the default). In-memory only (uo::map::StumpOverlay);
    // it reverts on its own once the TTL lapses. `treeGraphic` is the live tree
    // static id to replace. Exposed to JS as World.markStump.
    void MarkStump(i32 x, i32 y, i8 z, u16 treeGraphic, i64 ttlMs = 0);
    void BotStartGoto(i32 tx, i32 ty, bool hasZ = false, i32 tz = 0,
                      bool terrainBias = true);
    void BotStartFollow(u32 serial, u32 followDistance);
    void BotStopFollow(const char* reason);
    void BotNoteFatigueMessage();
    void BotAbortPath(const char* reason);
    void BotResetMovement();
    // Scripted-trip completion bridge: a JS `await goto()` registers a one-shot
    // callback that the trip end fires exactly once (arrived -> success, any
    // abort -> failure with reason). Settled by uo::js::ClientBindings.
    void BotSetDoneCb(std::function<void(bool success, const char* reason)> cb);
    void BotClearDoneCb();
    void BotSignalDone(bool success, const char* reason);
    void BotFollowTick();
    bool ChooseFollowGoal(i32* gx, i32* gy, i8* gz) const;
    void BotTick();           // called once per Tick() while in world
    void RenderTick();        // draws the world window (no-op unless enabled)
    void HandleRenderChatInput();
    void HandleManualWalk();  // arrow-key steering from the render window
    void HandleWorldClick();  // right-click in the render window -> goto that cell
    void HandleItemClicks();  // left-click (look) + double-click (use/open) on world objects
    // Target cursor (0x6C): the server arms a target after a spell/item use; the
    // next world click (or `target` console command) resolves it. See OnTargetCursor.
    void TargetRespondObject(u32 serial);  // answer with a clicked mobile/item
    void TargetRespondGround(i32 x, i32 y, bool hasZ, i8 z);  // answer with a tile
    void TargetRespondStatic(i32 x, i32 y, i8 z, u16 graphic);  // answer with a static (tree)
    void CancelTargetCursor(const char* reason);             // Esc / right-click
    bool ResolveObjectTarget(u32 serial, i32* x, i32* y, i8* z, u16* model) const;
    void DrawStatusBars();
    void DrawContainers();    // simple text HUD listing open containers' items
    void DrawSystemLog();
    void DrawChatInput();
    void DrawOverheadText();
    void DrawCursorOverlay(); // UO directional walk cursor under the mouse
    void BotPumpMoves();      // sends moves while a flight slot + cadence allow
    void BotPredictStep(u8 dir, bool run);  // advance predicted pos/z for a sent step
    void BotPollPathPlanner();
    // Gait for one A* step. Auto (i.e. run) unless this particular step is one
    // of the few that a human would walk -- see the definition for the reasons.
    sphere::Gait BotStepGait(bool lastStep, bool doorStep, bool shoveStep) const;
    u32  BotMoveGapMs() const;
    bool BotReplanToGoal();   // queue a full A* replan from current pose
    bool BotLookaheadPatchPath(); // short local reroute around visible blockers
    bool BotIsRuntimeBlocked(i32 x, i32 y, i8 z) const;
    bool BotIsMobileBlocking(i32 x, i32 y, i8 z) const;
    bool BotIsDynamicItemBlocking(i32 x, i32 y, i8 z) const;
    bool BotStepNeedsDoorOpen(i8 fromZ, i32 toX, i32 toY, i8 toZ) const;
    bool BotIsRejectedEdge(i32 fromX, i32 fromY, i8 fromZ,
                           i32 toX, i32 toY, i8 toZ) const;
    bool BotDoorRetryWasTried(i32 fromX, i32 fromY, i8 fromZ,
                              i32 toX, i32 toY, i8 toZ) const;
    void BotRememberDoorRetry(i32 fromX, i32 fromY, i8 fromZ,
                              i32 toX, i32 toY, i8 toZ);
    static bool BotRuntimeBlockedForPath(i32 x, i32 y, i8 z, void* user);
    static bool BotRuntimeBlockedStepForPath(i32 fromX, i32 fromY, i8 fromZ,
                                             i32 toX, i32 toY, i8 toZ,
                                             void* user);
    // Threat hook: called when we detect we're under attack mid-travel.
    // For now it just halts travel safely; engage/flee/recall are TODO.
    void BotInterruptForThreat(const char* reason);
    i64  NowMs() const;
    u8   NextSeq();

    Config cfg_;
    State  state_;

    net::Socket       sock_;
    net::PacketStream stream_;
    net::Huffman      huff_;

    // Server->client game stream is Huffman-compressed once the server
    // processes our 0x91 GameLogin. Off during the (plaintext) login phase.
    bool              decompress_;
    std::vector<u8>   rxScratch_;  // decompressed bytes for one recv

    ServerEntry servers_[32];
    int         serverCount_;
    int         selectedServer_;

    CharEntry charSlots_[5];
    int       charCount_;     // total slots reported (incl. empty)
    int       selectedChar_;

    u32   gameSeed_;
    u32   gameServerIp_;      // host-order
    u16   gameServerPort_;    // host-order

    struct PlayerSkill {
        u16 id;
        u16 valueTenths;
        u16 baseTenths;
        u16 capTenths;
        u8 lock;
        bool hasCap;
    };
    struct PlayerObj {
        u32 serial = 0;
        u16 body = 0;
        std::string name;
        i32 x = 0, y = 0;
        i8 z = 0;
        u8 facing = 0;
        bool running = false;
        i32 hpCur = -1, hpMax = -1;
        i32 manaCur = -1, manaMax = -1;
        i32 stamCur = -1, stamMax = -1;
        i32 strength = -1, dexterity = -1, intelligence = -1;
        i32 gold = -1, armor = -1, weight = -1, maxWeight = -1;
        u8 nameChangeFlag = 0, statusFlag = 0, sexRace = 0, race = 0;
        i32 statsCap = -1;
        u8 followers = 0, followersMax = 0;
        std::unordered_map<u16, PlayerSkill> skills;
    };
    PlayerObj player_;
    u32   playerSerial_;
    ActiveDialog activeDialog_;   // latest 0x7C menu, until answered (0x7D)
    bool openBackpackPending_ = false;   // open the backpack once after login
    bool backpackContentsKnown_ = false; // 0x3C for the backpack has arrived

    // M3 player state — populated from 0x1B/0x20/0x22.
    i32   playerX_;
    i32   playerY_;
    i8    playerZ_;
    u8    playerFacing_;        // 0..7 (low 3 bits of dir byte)
    bool  playerRunning_;
    bool  playerWarMode_ = false;
    // World light (0x4F overall, 0x4E personal). 0 = day/bright, 0x1F = black;
    // render darkness = clamp(overall - personal, 0..31). See Renderer::ApplyDarkness.
    u8    overallLightLevel_ = 0;
    u8    personalLightLevel_ = 0;
    bool  alwaysDay_ = true;    // force full daylight, ignore 0x4E/0x4F levels
                                // (toggle in-world with `day [on|off]`)
    i64   lastStepMs_ = 0;      // when we last actually changed cell (anim: walk vs idle)
    i32   prevPlayerX_ = 0; i32 prevPlayerY_ = 0;  // cell before the current step (slide interp)
    i64   playerMoveAnimTickMs_ = 0;
    u32   playerMoveAnimCounter_ = 0;
    struct IdleAnimState {
        i64 nextProbeMs = 0;
        i64 lastTickMs = 0;
        u8 action = 0;
        u16 maxFrames = 0;
        u16 delayPerFrame = 0;
        u16 maxDuration = 0;
        u16 currentFrame = 0;
        u16 currentDuration = 0;
        u16 pad = 0;
        u16 repeatCount = 0;
        u16 renderedFrame = 0;
        u8 renderedAction = 0;
        bool active = false;
        bool reverse = false;
        bool hasRenderedFrame = false;
    };
    struct ServerAnimState {
        i64 lastTickMs = 0;
        u8 action = 0;
        u16 maxFrames = 0;
        u16 delayPerFrame = 0;
        u16 maxDuration = 0;
        u16 currentFrame = 0;
        u16 currentDuration = 0;
        u16 pad = 0;
        u16 renderedFrame = 0;
        bool active = false;
        bool reverse = false;
        bool bounce = false;
        bool hasRenderedFrame = false;
    };
    IdleAnimState playerIdleAnim_;
    ServerAnimState playerServerAnim_;
    // Navigation owns predicted movement, bot route/follow state, and
    // learned transient blockers. Server packets still own authoritative
    // player position above.
    navigation::NavigationState nav_;
    std::function<void(bool, const char*)> botDoneCb_;  // one-shot scripted-trip completion

    // M3 bot data files + walker
    std::unique_ptr<uo::tiledata::TileDataLoader> tileData_;
    std::unique_ptr<uo::map::Map>                 worldMap_;
    std::unique_ptr<uo::world::World>             world_;
    std::unique_ptr<uo::navigation::PathPlanner>  pathPlanner_;
    bool worldLoaded_;

    // Renderer — lazily initialized on the first in-world tick when
    // cfg_.enableRenderer. Closing the window stops drawing but leaves the
    // bot running (cfg_.enableRenderer is cleared).
    std::unique_ptr<uo::art::ArtLoader>      art_;
    std::unique_ptr<uo::texmap::TexmapLoader> texmaps_;
    std::unique_ptr<uo::anim::AnimLoader>    anim_;
    std::unique_ptr<uo::animdata::AnimDataLoader> animData_;
    std::unique_ptr<uo::animinfo::AnimInfoLoader> animInfo_;
    std::unique_ptr<uo::hues::HuesLoader>    hues_;
    std::unique_ptr<uo::render::Renderer>    renderer_;
    std::unique_ptr<uo::render::TextRenderer> text_;
    std::unique_ptr<uo::render::Minimap>     minimap_;
    std::unique_ptr<uo::render::RadarColors> radarColors_;
    bool renderInit_;
    bool renderWindowOpen_;
    bool minimapVisible_;       // overlay minimap panel (toggle with 'M')
    bool minimapKeyDown_;       // 'M' edge-detect so a held key toggles once
    bool spaceKeyDown_;         // SPACE edge-detect (OpenDoor on press, once)
    bool tabKeyDown_ = false;   // TAB edge-detect (war/peace toggle)
    bool chatInputActive_;
    std::string chatInputLine_;

    // Mouse interaction (ported from the client's WorldGump click state machine).
    // hoverSerial_ is the object currently under the cursor — drawn with the
    // highlight hue so it "lights up", like g_ContextActionTargetSerial @hue 53.
    // A left-click is DEFERRED: the single-click "look" only fires once the
    // double-click window (mfb_double_click_ms) elapses with no second click, so
    // a double-click sends only the 0x06 use/open (matching WorldGump_OnHoverTick
    // @0x47A910 / WorldGump_OnLButtonUp @0x47A310 in client_2.0.7.exe).
    u32  hoverSerial_ = 0;
    // Target cursor armed by an inbound 0x6C (Packet_HandleTargetCursor @0x41E960).
    // While active, the next world click resolves into a 0x6C response; Esc/right-
    // click cancels. id/subtype are echoed back; type is the server's requested
    // mode (0=object, 1=ground) but the response type follows what we actually hit.
    // Per-session target cursor state machine (uo/actions.h). Carries a
    // generation counter so an action can only answer the cursor it caused --
    // a superseded cursor's reply is refused rather than sent to the wrong
    // request. Session-owned, so two clients never share a cursor.
    act::TargetState target_;
    bool escKeyDown_ = false;         // VK_ESCAPE edge-detect (cancel target once)
    bool pendingLClick_ = false;     // a single-click is waiting out the dbl-click window
    u32  pendingLClickSerial_ = 0;   // object picked on that press (0 = empty space)
    i64  pendingLClickMs_ = 0;       // press time, vs mfb_double_click_ms()

    // Single-click "look" name labels floated over world items. The 2.0.7 client
    // shows an item's name LOCALLY from tiledata on single-click — no packet —
    // as a short-lived overhead bark (Entity_ShowLocalLookMessage @0x4C95B0;
    // WorldGump_HandleTargetOrLookClick returns before the 0x09 for items, which
    // is mobile-only). We mirror that: an item click adds a label here; a mobile
    // click still sends 0x09. Drawn by DrawOverheadText, anchored to the item's
    // live position so it tracks if the item moves, expiring after kItemLabelMs.
    struct ItemLabel { u32 serial; i64 expireMs; std::string text; };
    std::vector<ItemLabel> itemLabels_;
    // Build an item's display name from tiledata, mirroring
    // Tiledata_FormatItemName @0x4C4870: article prefix from flags&0xC000
    // (a/an/the) plus the name with its %singular/plural% markup resolved.
    std::string FormatItemName(u16 graphic) const;
    void ShowItemLabel(u32 serial);
    u16  playerBody_;           // local player body graphic for the renderer
    struct EquipObj { u8 layer; u16 graphic; u16 hue; u32 serial = 0; };
    std::vector<EquipObj> playerEquip_;  // own worn items (layer, graphic, hue)
    u16  playerHue_ = 0;
    // Disarm memory: serial last taken off each hand layer so `arm` can put it
    // back. Indexed by layer (1 = one-handed/weapon, 2 = two-handed/shield);
    // index 0 unused. Mirrors g_ArmDisarm_SavedSerial @0xCD5A68.
    u32  armSavedSerial_[3] = {0, 0, 0};
    u8   warModeArg1_ = 4;      // cached 0x72 trailing args, as in client 2.0.7
    u8   warModeArg2_ = 0;
    u8   warModeArg3_ = 0;
    i64  lastManualMoveMs_;     // arrow-key walk throttle (render window)

    // All world items seen via 0x1A (lamp posts, doors, decor, ...), keyed by
    // serial — fed to the renderer so dynamic server objects are drawn too.
    struct ItemObj { u16 itemId; i32 x; i32 y; i8 z; u8 gfxOffset; u16 hue; };
    static constexpr usize kMaxItemCache = 32768;
    std::unordered_map<u32, ItemObj> items_;
    std::deque<u32> itemOrder_;

    // Corpses (item graphic 0x2006). Unlike the official client where CCorpse is
    // a CMobile subclass (CCorpse_OnRender @0x406560), we keep the corpse-only
    // anim state in a side map keyed by the corpse item serial; the live position
    // still lives in items_. The 0x1A object carries body in the amount field and
    // facing in the direction byte (CObjectManager_HandleMove @0x4C7D6C copies
    // them to stackCount/facingFlags), so the corpse renders the dead body's
    // death-pose frame from anim.mul. deathAction/equip/deadMobile are filled by
    // the 0xAF that preceded the corpse (DeathAnimationQueue_Add @0x4C3B50).
    struct CorpseObj {
        u16 body = 0;        // dead body graphic (0x1A amount / stackCount)
        u8  dir = 0;         // facing it died at (0x1A direction byte)
        u16 hue = 0;
        u8  deathAction = 0; // death anim group that played (0 = not set by 0xAF)
        u32 deadMobile = 0;  // dying mobile serial — corpse is hidden until its
                             // death animation finishes (queue suppression)
        std::vector<EquipObj> equip;  // worn gear snapshot from the dead mobile
    };
    std::unordered_map<u32, CorpseObj> corpses_;
    // Death anim group for a body, mirroring Mobile_PlayDeathAnimation @0x4C65C0.
    static u8 DeathActionForBody(u16 body, bool normalDeath);

    // Open containers (bank, backpack, chests, corpses) registered by 0x24, with
    // contents listed by 0x3C and patched by 0x25. We don't draw the real gump
    // art yet — DrawContainers() lists each contained item as text. gumpId is the
    // 0x24 "model type" (500/501 = bank, 10/48 = paperdoll, 0xFFFF = close).
    // Keyed by the raw container serial, matching what 0x3C/0x25 carry. Mirrors
    // Packet_HandleDrawContainer / Packet_HandleContainerItems in
    // client_2.0.7.exe (0x417f70 / 0x418990), minus the gump rendering.
    struct ContainerItem { u32 serial; u16 graphic; u8 gfxOffset; u16 amount; u16 x; u16 y; u16 hue; };
    struct OpenContainer { u32 serial; u16 gumpId; };
    std::vector<OpenContainer> openContainers_;
    std::unordered_map<u32, std::vector<ContainerItem>> containerItems_;

    // Vendor buy window: the server sends, in order, a 0x3C (stock container
    // contents) then a 0x74 SHOP_DATA (prices + names, SAME order), optionally a
    // second pair for the offered/resale container, then a 0x24 gump 0x30 whose
    // "container" serial is the VENDOR MOBILE. We join 0x3C+0x74 by index into
    // VendorItem rows (carrying the shop-container layer to send back in 0x3B)
    // and accumulate them in pendingVendor_ until the gump 0x30 finalizes the
    // session and emits the `vendor_buy` event. See shopkeeper.c / human.m.
    std::vector<VendorItem> pendingVendor_;
    int pendingVendorGroups_ = 0;        // 0x74 groups seen this session (0 -> layer 0x1A, else 0x1B)
    // One buy request row (JS Vendor.buy): how many of `serial` to buy from `layer`.
    struct VendorBuyReq { u32 serial; u16 qty; u8 layer; };
    void SendVendorBuy(u32 vendor, const std::vector<VendorBuyReq>& items);  // 0x3B

    // Recent mobiles (players/NPCs) from 0x77/0x78. A reject at a tile that
    // holds a mobile is a moving obstacle (or a stamina-gated shove), never a
    // wall — such tiles are never blacklisted.
    struct MobileObj {
        u32 serial; i32 x; i32 y; i8 z; u8 dir; u16 body; u16 hue; i64 seenMs;
        i64 movedMs = 0;     // when (x,y) last changed (anim: walk vs idle)
        i32 prevX = 0; i32 prevY = 0;  // cell before the current step (slide interp)
        bool running = false; // high bit of the server direction byte
        bool warMode = false; // 0x77/0x78 status flag bit 0x40
        u8 noto = 0;          // 0x78 notoriety: 1 blue,2 green,3/4 gray,5 orange,6 red,7 yellow
        i32 hpCur = -1, hpMax = -1;  // 0xA1/0x2D health (often a 0..max ratio for foreign mobs)
        i64 lastAnimMs = 0;   // 0x6E: when it last played an action animation (0 = never)
        u8 lastAnimAction = 0;// 0x6E action code of that animation (swing/cast/get-hit/...)
        i64 deadRemoveMs = 0;  // 0xAF keeps the mobile until death anim ends
        i64 moveAnimTickMs = 0;
        u32 moveAnimCounter = 0;
        IdleAnimState idleAnim;
        ServerAnimState serverAnim;
        // Worn items as (layer, item graphic, hue). Preserved across 0x77
        // position updates; rebuilt on 0x78, patched by 0x2E.
        std::vector<EquipObj> equip;
    };
    std::deque<MobileObj> mobileCache_;
    std::unordered_map<u32, std::string> mobileNames_;
    // Paperdoll title ("<name> the <job>", e.g. "Aldo the healer") learned from
    // an 0x88 OPEN_PAPERDOLL after we double-click a mobile. The job suffix is the
    // only client-visible way to tell a healer from a tavernkeeper, so the restock
    // bot uses it to pick the right vendor. nullptr until the paperdoll arrives.
    std::unordered_map<u32, std::string> paperdollTitles_;
    const char* PaperdollTitle(u32 serial) const;
    const MobileObj* FindMobileAt(i32 x, i32 y, i8 z) const;
    const MobileObj* FindMobileBySerial(u32 serial) const;

    // Object update/cull radius (Chebyshev tiles), set by 0xC8; default 18.
    // Mirrors g_ObjectUpdateRange in client_2.0.7 (Packet_HandleClientViewRange).
    int viewRange_ = 18;
    // Drop tracked mobiles / open world-containers that have left viewRange_ of
    // the player, like CObjectManager_UpdateMovement @0x4c8b00 (out-of-range
    // entities -> _Destroy_RefCounter). The server re-sends them (0x78/0x1A)
    // when they re-enter range, so the local cache stays bounded to "what's
    // around us" instead of growing stale. Self-gated on player movement via
    // lastPurgeX_/Y_; called once per pump iteration.
    void PurgeOutOfRange();
    i32 lastPurgeX_ = 0x7FFFFFFF, lastPurgeY_ = 0x7FFFFFFF;
    void UpdateMobile(u32 serial, i32 x, i32 y, i8 z, u8 dir, u16 body,
                      u16 hue = 0, bool hasHue = false,
                      u8 statusFlags = 0, bool hasStatusFlags = false,
                      int notoriety = -1);
    void SetMobileEquip(u32 serial, std::vector<EquipObj> equip);
    void SetMobileEquipLayer(u32 mobileSerial, u32 itemSerial, u8 layer,
                             u16 graphic, u16 hue);
    // Serial of our worn item at a layer (0 if nothing equipped there).
    u32 PlayerEquipSerialAt(u8 layer) const;
    // Lowercased tiledata static name for an item graphic ("" if no tiledata).
    std::string ItemNameLower(u16 graphic) const;
    // Equip layer for an item graphic, read from tiledata (StaticTile.quality,
    // as the client does in Gump_HandleMouseOver @0x45486d). 0 = unknown.
    u8 ItemEquipLayer(u16 graphic) const;
    void ForgetEquippedItem(u32 itemSerial);
    // True if an item graphic matches the query (exact graphic when hasType,
    // else a case-insensitive tiledata-name substring).
    bool ItemMatches(u16 graphic, bool hasType, u16 type,
                     const std::string& lowerName) const;
    // Zones for FindItem (bitmask).
    enum SearchZone : unsigned { kZoneBackpack = 1, kZoneEquip = 2, kZoneWorld = 4 };
    // Resolve an item by type/name across the requested zones (backpack first,
    // then worn equipment, then the nearest world item). Optionally reports the
    // matched graphic, worn layer (0 unless from kZoneEquip) and a where-label.
    u32 FindItem(bool hasType, u16 type, const std::string& lowerName,
                 unsigned zones, u16* graphicOut, u8* layerOut,
                 const char** whereOut) const;
    // Parse a leading item token: quoted 'name'/"name", a 0xserial, a numeric
    // graphic type, or a single bareword name. Sets exactly one of *serialOut,
    // (*hasTypeOut + *typeOut), or *lowerNameOut, and points *restOut past the
    // token. Returns false on a malformed token.
    bool ParseItemToken(const char* arg, u32* serialOut, bool* hasTypeOut,
                        u16* typeOut, std::string* lowerNameOut,
                        const char** restOut) const;
    void HandleUseCommand(const char* arg);
    void HandlePickupCommand(const char* arg);
    void HandleDropCommand(const char* arg);
    void HandleEquipCommand(const char* arg);
    void HandleUnequipCommand(const char* arg);
    // arm/disarm: move the weapon (layer 1) / shield (layer 2) between hand and
    // backpack, remembering what was disarmed so `arm` re-equips it. Mirrors
    // Macro_ActionArmDisarm_Validate @0x4b6c90. `doArm` re-equips the saved
    // item; otherwise the equipped item is dropped into the backpack.
    void ArmDisarmHand(bool doArm, u8 layer);
    bool mobilesListPending_;
    i64  mobilesListDeadlineMs_;
    std::vector<u32> mobilesListSerials_;
    std::unordered_set<u32> mobilesListAwaiting_;
    std::unordered_map<u32, i64> overheadNameProbeMs_;
    i64 lastStatusProbeMs_;     // 0x34 status request while HUD has no stats
    i64 lastActivityMs_;        // any TCP send/recv — for 0x73 keepalive

    // Console chatter gate. The JSON packet log always records everything;
    // the window shows only meaningful events unless this is toggled on
    // (stdin: `verbose on|off`). Keeps per-packet noise (0x11/0x20/0x21/0x22
    // and unhandled ids) out of the window by default.
    bool verboseConsole_;

    // --- Sphere adapter (M1) state ---------------------------------------
    std::deque<u8> directSteps_;         // ActionWalk queue (dirs still to send)
    sphere::Gait directStepsGait_ = sphere::Gait::Auto;  // gait for queued steps
    i64   lastDirectStepMs_ = 0;
    i32   walkBatchStartX_ = 0;          // position when the current batch began
    i32   walkBatchStartY_ = 0;
    bool  walkBatchActive_ = false;
    bool  gotoRequested_ = false;        // ActionGoto issued, outcome pending
    bool  gotoArrived_ = false;          // last ActionGoto reached its goal
    i32   gotoTargetX_ = 0;
    i32   gotoTargetY_ = 0;
    u8    pingSeq_ = 0;                  // 0x73 keepalive counter
    int   pingOutstanding_ = 0;          // keepalives sent, answer not yet seen
    i64   lastPingEchoMs_ = 0;           // rate limit for echoing server pings
    bool  loggingOut_ = false;           // ActionLogout was called
    i64   logoutSentMs_ = 0;             // when 0xD1 went out
    bool  logoutAcked_ = false;          // server answered 0xD1
    bool  charCreateSent_ = false;       // 0x00 sent; don't loop on it
    std::unique_ptr<bot::Scenario> scenario_;

    // --- M2 action state (all session-owned) -------------------------------
    act::Action    action_;
    act::DragState drag_;
    act::LifeState life_ = act::LifeState::Alive;
    u32 bankContainer_ = 0;         // container the server opened as our bank
    u32 vendorOfferVendor_ = 0;     // vendor whose offer is in vendorOffer_
    std::vector<VendorItem> vendorOffer_;
    std::vector<VendorItem> vendorSellOffer_;   // what the vendor will buy
    i32 manaAtActionStart_ = -1;    // for observing a spell's mana cost
    i32 goldAtActionStart_ = -1;    // for observing a purchase

    // --- M2.5 travel state (all session-owned) ----------------------------
    // The atlas / navgrid / planner pointers are into the process-wide
    // immutable SharedWorld; everything else here is this character's alone.
    void TravelTick();
    void WarModeTick();
    bool EnsureWorldKnowledge();
    bool TravelBegin(const char* label, i32 x, i32 y, i32 arriveRadius,
                     bool hasZ = false, i8 z = 0);
    void TravelPlanRoute();
    void TravelDriveLeg();
    void TravelUseTransit();
    void TravelFinish(bool ok, const char* why);
    // Keep an entity-chasing journey aimed at where the mobile actually is.
    void TravelRetargetEntity();
    // Note the place we just reached, so the character remembers being there.
    void TravelNotePlaceReached(i32 x, i32 y);
    // Turn a paperdoll title ("Aldo the healer") into a live service sighting.
    void NoteServiceFromTitle(u32 serial, const char* title);

    const world_atlas::SharedWorld* world_knowledge_ = nullptr;
    travel::Journey             journey_;
    travel::PersonalKnowledge   knowledge_;
    travel::WarModeWatchdog     war_;
    std::string travelFailure_;
    std::string travelLabel_;
    bool  travelSucceeded_ = false;
    u32   travelEntitySerial_ = 0;    // non-zero while chasing a mobile
    i32   travelEntityWithin_ = 2;
    i64   travelLastSampleMs_ = 0;
    i32   travelLegTargetX_ = 0;      // what we asked ActionGoto for
    i32   travelLegTargetY_ = 0;
    bool  travelWalkOutstanding_ = false;
    bool  travelStartedDead_ = false;  // ghost trips are legitimate; see TravelTick
    bool  travelHasGoalZ_ = false;     // the destination's floor, when known
    i8    travelGoalZ_ = 0;
    // Transit entry tiles near the current leg that this trip must NOT step
    // on. Scripts-X puts a teleporter in the middle of Yew that sends you to
    // Heartwood, so walking through town is otherwise a gamble. Refreshed per
    // leg; the pad the current leg is deliberately using is excluded.
    std::vector<wm::Point> travelAvoidPads_;
    void TravelRefreshAvoidPads(i32 legX, i32 legY);
    bool TravelPadIsAvoided(i32 x, i32 y) const;
    // Bounded "walk toward the door and see" for a character the router cannot
    // plan out of -- an upper storey with no reachable stair, say.
    bool TravelTryEscape();
    int   travelEscapes_ = 0;
    std::vector<wm::Point> travelEscapeTried_;
    // Moongates are only planned through when the caller says this character
    // will use them, because a gate the shard's worldgen never placed is a
    // route that cannot be executed. Off by default; a scenario or a brain
    // turns it on for a character that knows the gates.
    bool  travelUseMoongates_ = false;
    u32   travelGateSerial_ = 0;       // gate we double-clicked, awaiting its gump
    std::string travelGateDestination_;// what to pick when that gump arrives

    // Generic gump (0xB0) currently open. The public moongate's destination
    // list arrives this way, and answering it is how a player uses the gate.
    struct ActiveGump {
        bool active = false;
        u32  serial = 0;      // object the gump belongs to (echoed back)
        u32  context = 0;     // dialog id (echoed back)
        std::vector<GumpOption> options;
    };
    ActiveGump gump_;
    void OnGenericGump(const u8* data, usize size);   // 0xB0
    void OnSecureTrade(const u8* data, usize size);   // 0x6F
    void SendTradeAction(u8 action, u32 container, u32 flag);
    void TradeNoteItemAdded(u32 container, u32 item);
    void TradeNoteItemRemoved(u32 item);
    trade::TradeState trade_;      // session-owned; never shared
    void AnswerGateGump();   // pick the route's destination out of an open gump
    void SendGumpResponse(u32 serial, u32 context, u32 button,
                          const u32* checks, usize checkCount);   // 0xB1

    // --- session lifecycle / identity ------------------------------------
    mutable Logger log_;                 // this session's own log file + tag
    const char* sessionTag_ = "";
    bool  started_ = false;
    bool  finished_ = false;
    int   exitCode_ = 0;
    std::chrono::steady_clock::time_point lastActivity_{};
    bool  stalledLogged_ = false;

    enum class JournalOwnerKind : u8 { System, Player, Mobile, Item, Unknown };
    struct JournalEntry {
        i64 timeMs;
        u32 sourceSerial;
        u16 sourceBody;
        u8 type;
        u16 hue;
        u16 font;
        JournalOwnerKind ownerKind;
        bool hasPosition;
        i32 x, y;
        i8 z;
        std::string speaker;
        std::string text;
    };
    static constexpr usize kMaxJournalEntries = 1024;
    std::deque<JournalEntry> journal_;

    std::thread             stdin_thread_;
    std::mutex              stdin_mtx_;
    std::queue<std::string> stdin_lines_;
    std::atomic<bool>       stop_stdin_;

    // Embedded JS scripting engine (QuickJS-NG). Ticks on the main loop after
    // BotTick; `run <file>` (re)starts a script in a fresh runtime. Script
    // errors are caught and printed ([js]) and never crash the client.
    js::JsEngine js_;
};

}
